# Default values for graphqlmetrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wundergraph/cosmo/graphqlmetrics
  registry: ghcr.io
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  #version: "latest"

# -- Add labels to all deployed resources
commonLabels: {}

deploymentStrategy: {}

imagePullSecrets: []

# -- String to partially override common.names.fullname template (will maintain the release name)
nameOverride: ""

# -- String to fully override common.names.fullname template
fullnameOverride: ""

# -- Allows to set additional environment / runtime variables on the container. Useful for global application non-specific settings.
extraEnvVars: []
  # Recommended for production to mitigate the risk of OOM kills. Requires Go 1.19+.
  # Keep the value lower than the maximum memory limit you set. E.g. if you have 3GB memory limit, set this to 2750MiB.
#  - name: GOMEMLIMIT
#    value: "2750MiB"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

serviceAnnotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4005

ingress:
#  enabled: true
#  className: ""
#  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
#    - host: graphqlmetrics.wundergraph.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#initContainers:
#  - name: init-clickhouse
#    image: busybox:1.28
#    imagePullPolicy: "IfNotPresent"
#    command: ['sh', '-c', 'until nslookup {{ include "clickhouse.fullname" . }}; do echo waiting for clickhouse; sleep 2; done;']

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# -- Sets the [pod disruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for Deployment pods
podDisruptionBudget: {}

# -- Set to existing PriorityClass name to control pod preemption by the scheduler
priorityClassName: ""

# -- Sets the [termination grace period](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution) for Deployment pods
terminationGracePeriodSeconds: 10

probes:
  # -- Configure readiness probe
  readiness:
    initialDelaySeconds: 10
  # -- Configure liveness probe
  liveness:
    initialDelaySeconds: 10

########################
# Global configuration #
########################

#global:
#  controlplane:
#    jwtSecret: <secret>

#############################
# Application configuration #
#############################

configuration:
  clickhouseDsn: "clickhouse://default:changeme@cosmo-clickhouse:9000/cosmo?dial_timeout=15s&compress=lz4"
  logLevel: "info"
  listenAddr: "0.0.0.0:4005"

  # -- Use this section to configure prometheus metrics.
  prometheus:
    # -- Enables prometheus metrics support. Default is false.
    enabled: false
    # -- The host to bind to defautls to 127.0.0.1 to avoid opening the metrics endpoint by default.
    host: 127.0.0.1
    # -- The port where metrics are exposed. Default is port 8088.
    port: 8088
    # -- The HTTP path where metrics are exposed. Default is "/metrics".
    path: "/metrics"
    # Use this section to disable/enable pod monitoring over [GCP managed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#config-mgd-collection).
    gcpMonitoring:
      # -- Enables gcp support . Default is false.
      enabled: false
      # -- Scrape interval. Default is "60s".
      interval: 60s
      # -- Scrape timeout. Default is "50s".
      timeout: 50s


# -- Existing secret in the same namespace containing the graphqlmetrics Secrets - clickhouseDsn,jwtSecret. The secret keys have to match with current secret.
existingSecret: ""
