package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/articlesmeta/subgraph/generated"
	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/articlesmeta/subgraph/model"
)

// FindArticleByID is the resolver for the findArticleByID field.
func (r *entityResolver) FindArticleByID(ctx context.Context, id string) (*model.Article, error) {
	fixture := articleMetaFixtures[id]
	return &model.Article{
		ID:            id,
		ViewCount:     fixture.ViewCount,
		Rating:        fixture.Rating,
		ReviewSummary: fixture.ReviewSummary,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
