name: "Build and Push Image (PR only)"
description: "This action to build and push docker image for CI in Pull Request only."
inputs:
  image_description:
    description: "The description of the container"
  image_name:
    description: "The name of the container"
    required: true
  token:
    description: "The token to use for the GitHub container registry"
    required: true
  dockerfile:
    description: "The Dockerfile to use"
    default: "Dockerfile"
  docker_context:
    description: "The Docker context to use"
    default: "."
  docker_username:
    description: "The username to use for the Docker container registry"
    required: true
  docker_password:
    description: "The password to use for the Docker container registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Container registry (With write access)
      uses: docker/login-action@v3
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        registry: docker.io
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ inputs.image_name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
          # use custom value instead of git tag
          type=match,pattern=[a-zA-Z-_]+@(.*),group=1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set BUILD_TIME env
      shell: bash
      run: echo BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> ${GITHUB_ENV}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        # This is a limitation of GitHub. Only organization members can push to GitHub Container Registry
        # For now, we will disable the push to the GitHub Container Registry for external contributors
        push: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.docker_context }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        outputs:
          type=image,name=target,annotation-index.org.opencontainers.image.description=${{ inputs.image_description }}
          type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/wundergraph/cosmo
          type=image,name=target,annotation-index.org.opencontainers.image.licenses=Apache-2.0
        build-args: |
          VERSION=${{ github.sha }}
          DATE=${{ env.BUILD_TIME }}
          COMMIT=${{ github.sha }}
