version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
        - "router"
        - "router-tests"
        - "aws-lambda-router"
        - "composition-go"
        - "connect-go"
    schedule:
      interval: "weekly"
    groups:
      wundergraph:
        patterns:
          - "**/wundergraph/**"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"