version: 2

updates:
  - package-ecosystem: "gomod"
    commit-message:
      prefix: 'chore(deps): go update'
    directories:
        - "router"
        - "aws-lambda-router"
        - "composition-go"
        - "connect-go"
    schedule:
      interval: "weekly"
    groups:
      wundergraph:
        patterns:
          - "**/wundergraph/**"

  - package-ecosystem: "github-actions"
    commit-message:
      prefix: 'ci: action update'
    directory: "/"
    schedule:
      interval: "weekly"