// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PricePoint struct {
	Date  string  `json:"date"`
	Value float64 `json:"value"`
}

type Product struct {
	ID           string        `json:"id"`
	Price        float64       `json:"price"`
	PriceHistory []*PricePoint `json:"priceHistory"`
}

func (Product) IsEntity() {}

type Query struct {
}
