// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Experience interface {
	IsExperience()
	GetYearsOfExperience() float64
}

type Details struct {
	ID      int      `json:"id"`
	Hobbies []*Hobby `json:"hobbies,omitempty"`
}

func (Details) IsEntity() {}

type Hobby struct {
	Type string `json:"type"`
}

type Sdk struct {
	Upc             string                `json:"upc"`
	ClientLanguages []ProgrammingLanguage `json:"clientLanguages"`
}

func (Sdk) IsEntity() {}

type ExerciseType string

const (
	ExerciseTypeCalisthenics     ExerciseType = "CALISTHENICS"
	ExerciseTypeHiking           ExerciseType = "HIKING"
	ExerciseTypeSport            ExerciseType = "SPORT"
	ExerciseTypeStrengthTraining ExerciseType = "STRENGTH_TRAINING"
)

var AllExerciseType = []ExerciseType{
	ExerciseTypeCalisthenics,
	ExerciseTypeHiking,
	ExerciseTypeSport,
	ExerciseTypeStrengthTraining,
}

func (e ExerciseType) IsValid() bool {
	switch e {
	case ExerciseTypeCalisthenics, ExerciseTypeHiking, ExerciseTypeSport, ExerciseTypeStrengthTraining:
		return true
	}
	return false
}

func (e ExerciseType) String() string {
	return string(e)
}

func (e *ExerciseType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExerciseType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExerciseType", str)
	}
	return nil
}

func (e ExerciseType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type GameGenre string

const (
	GameGenreAdventure  GameGenre = "ADVENTURE"
	GameGenreBoard      GameGenre = "BOARD"
	GameGenreFps        GameGenre = "FPS"
	GameGenreCard       GameGenre = "CARD"
	GameGenreRpg        GameGenre = "RPG"
	GameGenreRoguelite  GameGenre = "ROGUELITE"
	GameGenreSimulation GameGenre = "SIMULATION"
	GameGenreStrategy   GameGenre = "STRATEGY"
)

var AllGameGenre = []GameGenre{
	GameGenreAdventure,
	GameGenreBoard,
	GameGenreFps,
	GameGenreCard,
	GameGenreRpg,
	GameGenreRoguelite,
	GameGenreSimulation,
	GameGenreStrategy,
}

func (e GameGenre) IsValid() bool {
	switch e {
	case GameGenreAdventure, GameGenreBoard, GameGenreFps, GameGenreCard, GameGenreRpg, GameGenreRoguelite, GameGenreSimulation, GameGenreStrategy:
		return true
	}
	return false
}

func (e GameGenre) String() string {
	return string(e)
}

func (e *GameGenre) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameGenre(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameGenre", str)
	}
	return nil
}

func (e GameGenre) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProgrammingLanguage string

const (
	ProgrammingLanguageCsharp     ProgrammingLanguage = "CSHARP"
	ProgrammingLanguageGo         ProgrammingLanguage = "GO"
	ProgrammingLanguageRust       ProgrammingLanguage = "RUST"
	ProgrammingLanguageTypescript ProgrammingLanguage = "TYPESCRIPT"
)

var AllProgrammingLanguage = []ProgrammingLanguage{
	ProgrammingLanguageCsharp,
	ProgrammingLanguageGo,
	ProgrammingLanguageRust,
	ProgrammingLanguageTypescript,
}

func (e ProgrammingLanguage) IsValid() bool {
	switch e {
	case ProgrammingLanguageCsharp, ProgrammingLanguageGo, ProgrammingLanguageRust, ProgrammingLanguageTypescript:
		return true
	}
	return false
}

func (e ProgrammingLanguage) String() string {
	return string(e)
}

func (e *ProgrammingLanguage) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgrammingLanguage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgrammingLanguage", str)
	}
	return nil
}

func (e ProgrammingLanguage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
