// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file wg/cosmo/ai/v1/ai.proto (package wg.cosmo.ai.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EnumStatusCode } from "../../common/common_pb.js";
import { file_wg_cosmo_common_common } from "../../common/common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wg/cosmo/ai/v1/ai.proto.
 */
export const file_wg_cosmo_ai_v1_ai: GenFile = /*@__PURE__*/
  fileDesc("Chd3Zy9jb3Ntby9haS92MS9haS5wcm90bxIOd2cuY29zbW8uYWkudjEiWwoIUmVzcG9uc2USLQoEY29kZRgBIAEoDjIfLndnLmNvc21vLmNvbW1vbi5FbnVtU3RhdHVzQ29kZRIUCgdkZXRhaWxzGAIgASgJSACIAQFCCgoIX2RldGFpbHMiNwoUR2VuZXJhdGVRdWVyeVJlcXVlc3QSDwoHdmVyc2lvbhgBIAEoCRIOCgZwcm9tcHQYAiABKAkigQEKFUdlbmVyYXRlUXVlcnlSZXNwb25zZRIqCghyZXNwb25zZRgBIAEoCzIYLndnLmNvc21vLmFpLnYxLlJlc3BvbnNlEjIKBXF1ZXJ5GAIgASgLMh4ud2cuY29zbW8uYWkudjEuU2F0aXNmaWVkUXVlcnlIAIgBAUIICgZfcXVlcnkiqQEKDlNhdGlzZmllZFF1ZXJ5EhMKC2Rlc2NyaXB0aW9uGAEgASgJEhAKCGRvY3VtZW50GAIgASgJEhYKDm9wZXJhdGlvbl9uYW1lGAMgASgJEj4KDm9wZXJhdGlvbl90eXBlGAQgASgOMiYud2cuY29zbW8uYWkudjEuU2F0aXNmaWVkT3BlcmF0aW9uVHlwZRIYChB2YXJpYWJsZXNfc2NoZW1hGAUgASgJKrgBChZTYXRpc2ZpZWRPcGVyYXRpb25UeXBlEigKJFNBVElTRklFRF9PUEVSQVRJT05fVFlQRV9VTlNQRUNJRklFRBAAEiIKHlNBVElTRklFRF9PUEVSQVRJT05fVFlQRV9RVUVSWRABEiUKIVNBVElTRklFRF9PUEVSQVRJT05fVFlQRV9NVVRBVElPThACEikKJVNBVElTRklFRF9PUEVSQVRJT05fVFlQRV9TVUJTQ1JJUFRJT04QAzJrCglBSVNlcnZpY2USXgoNR2VuZXJhdGVRdWVyeRIkLndnLmNvc21vLmFpLnYxLkdlbmVyYXRlUXVlcnlSZXF1ZXN0GiUud2cuY29zbW8uYWkudjEuR2VuZXJhdGVRdWVyeVJlc3BvbnNlIgBiBnByb3RvMw", [file_wg_cosmo_common_common]);

/**
 * @generated from message wg.cosmo.ai.v1.Response
 */
export type Response = Message<"wg.cosmo.ai.v1.Response"> & {
  /**
   * @generated from field: wg.cosmo.common.EnumStatusCode code = 1;
   */
  code: EnumStatusCode;

  /**
   * details is an optional field which can be used to provide more details about the error.
   *
   * @generated from field: optional string details = 2;
   */
  details?: string | undefined;
};

/**
 * Describes the message wg.cosmo.ai.v1.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema: GenMessage<Response> = /*@__PURE__*/
  messageDesc(file_wg_cosmo_ai_v1_ai, 0);

/**
 * @generated from message wg.cosmo.ai.v1.GenerateQueryRequest
 */
export type GenerateQueryRequest = Message<"wg.cosmo.ai.v1.GenerateQueryRequest"> & {
  /**
   * Copied from RouterConfig.version in the active router configuration.
   *
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: string prompt = 2;
   */
  prompt: string;
};

/**
 * Describes the message wg.cosmo.ai.v1.GenerateQueryRequest.
 * Use `create(GenerateQueryRequestSchema)` to create a new message.
 */
export const GenerateQueryRequestSchema: GenMessage<GenerateQueryRequest> = /*@__PURE__*/
  messageDesc(file_wg_cosmo_ai_v1_ai, 1);

/**
 * @generated from message wg.cosmo.ai.v1.GenerateQueryResponse
 */
export type GenerateQueryResponse = Message<"wg.cosmo.ai.v1.GenerateQueryResponse"> & {
  /**
   * @generated from field: wg.cosmo.ai.v1.Response response = 1;
   */
  response?: Response | undefined;

  /**
   * @generated from field: optional wg.cosmo.ai.v1.SatisfiedQuery query = 2;
   */
  query?: SatisfiedQuery | undefined;
};

/**
 * Describes the message wg.cosmo.ai.v1.GenerateQueryResponse.
 * Use `create(GenerateQueryResponseSchema)` to create a new message.
 */
export const GenerateQueryResponseSchema: GenMessage<GenerateQueryResponse> = /*@__PURE__*/
  messageDesc(file_wg_cosmo_ai_v1_ai, 2);

/**
 * @generated from message wg.cosmo.ai.v1.SatisfiedQuery
 */
export type SatisfiedQuery = Message<"wg.cosmo.ai.v1.SatisfiedQuery"> & {
  /**
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * @generated from field: string document = 2;
   */
  document: string;

  /**
   * @generated from field: string operation_name = 3;
   */
  operationName: string;

  /**
   * @generated from field: wg.cosmo.ai.v1.SatisfiedOperationType operation_type = 4;
   */
  operationType: SatisfiedOperationType;

  /**
   * @generated from field: string variables_schema = 5;
   */
  variablesSchema: string;
};

/**
 * Describes the message wg.cosmo.ai.v1.SatisfiedQuery.
 * Use `create(SatisfiedQuerySchema)` to create a new message.
 */
export const SatisfiedQuerySchema: GenMessage<SatisfiedQuery> = /*@__PURE__*/
  messageDesc(file_wg_cosmo_ai_v1_ai, 3);

/**
 * @generated from enum wg.cosmo.ai.v1.SatisfiedOperationType
 */
export enum SatisfiedOperationType {
  /**
   * @generated from enum value: SATISFIED_OPERATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SATISFIED_OPERATION_TYPE_QUERY = 1;
   */
  QUERY = 1,

  /**
   * @generated from enum value: SATISFIED_OPERATION_TYPE_MUTATION = 2;
   */
  MUTATION = 2,

  /**
   * @generated from enum value: SATISFIED_OPERATION_TYPE_SUBSCRIPTION = 3;
   */
  SUBSCRIPTION = 3,
}

/**
 * Describes the enum wg.cosmo.ai.v1.SatisfiedOperationType.
 */
export const SatisfiedOperationTypeSchema: GenEnum<SatisfiedOperationType> = /*@__PURE__*/
  enumDesc(file_wg_cosmo_ai_v1_ai, 0);

/**
 * @generated from service wg.cosmo.ai.v1.AIService
 */
export const AIService: GenService<{
  /**
   * @generated from rpc wg.cosmo.ai.v1.AIService.GenerateQuery
   */
  generateQuery: {
    methodKind: "unary";
    input: typeof GenerateQueryRequestSchema;
    output: typeof GenerateQueryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wg_cosmo_ai_v1_ai, 0);
