vulnerabilities:
  - id: CVE-2026-24051
    statement: Intended to be fixed in `ENG-9057`. The vulnerability happens on macOS/Darwin, as most images are used on Linux machines, we're ok with making this compromise. This was discussed with the team and OK'ed.
  - id: CVE-2025-15558
    statement: >
      Windows-only vulnerability in github.com/docker/cli (dependency of go-containerregistry in router).
      Per the CVE description, "this issue does not impact non-Windows binaries".
      Most images are used on Linux.
      Updating go-containerregistry fixes the issue but expects us to set router go version to 1.25.6 for a fix on a sparsely used platform.
      This can be reevaluated once we update to go 1.25.6 / 1.26.
