packages:
  - cli
  - composition
  - composition-go/shim
  - controlplane
  - controlplane/emails
  - proto
  - shared
  - studio
  - connect
  - cdn-server
  - cdn-server/cdn
  - admission-server
  - protographic
  - playground
