packages:
  - aws-lambda-router
  - cli
  - composition
  - docs-website
  - graphqlmetrics
  - composition-go/shim
  - controlplane
  - controlplane/emails
  - proto
  - router
  - router-plugin
  - shared
  - studio
  - connect
  - cdn-server
  - cdn-server/cdn
  - admission-server
  - protographic
  - playground
