# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"
dev_mode: false
# log_level: debug
# Path to the previous generated file
#router_config_path: config.json
graph:
  # Result of `wgc router token create`. Can be omitted for local testing.
  token: "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlMTdiZDNmZC05NDkzLTQzZWEtOTI1Yy04NTgzN2E2ZTlmZjEiLCJmZWRlcmF0ZWRfZ3JhcGhfaWQiOiI5OTFiZGMzMi1lYjBhLTQ3YTgtYmZmMi02M2RlY2VhNjljMzQiLCJhdWQiOiJjb3NtbzpncmFwaC1rZXkiLCJvcmdhbml6YXRpb25faWQiOiI2MGRhMWUwMy1mNTZlLTRkYjEtOTY5NS0yODY4YjBmMjBmYTQiLCJpYXQiOjE3MzMxMzkwNTN9.hPLPp6Ubqn5xSO3gBj1bjLGI6HJM3p-GVZE3NhdGjpA"

# define configurations on how errors are reported to the client from the subgraphs
#subgraph_error_propagation:
#  mode: pass-through
#  propagate_status_codes: false
#  omit_locations: true
#  allowed_extension_fields:
#    - "code"
#    - "message"
#    - "statusCode"
#    - "service"

#cors:
#  allow_methods:
#    - "POST"
#    - "GET"
#  allow_origins:
#    - "http://localhost:5173"
#  allow_headers:
#    - "*"
#  max_age: 5m
#  allow_credentials: true

#automatic_persisted_queries:
#  enabled: true
#  cache:
#    size: 10MB # Set the maximum size of the local cache in megabytes
#    ttl: 900 # Time-to-live for each cached query, in seconds (15 minutes)


events:
  providers:
    kafka:
      - id: "my-kafka"
        brokers:
          - "kafka:9092"
    nats:
      - id: "uta-onyx-subscription"
        url: "nats://0.0.0.0:4222"
      - id: "default"
        url: "nats://0.0.0.0:4222"
      - id: "my-nats"
        url: "nats://0.0.0.0:4222"

#engine:
#  enable_subgraph_fetch_operation_name: false
#  debug:
#    report_websocket_connections: true