# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used for the demo environment

version: "1"


telemetry:
  service_name: cosmo-router
  metrics:
    experiment_cardinality_limit: 2000
    prometheus:
      enabled: true
      path: /metrics
      listen_addr: localhost:8088
      graphql_cache: false
      connection_stats: false
      streams: false
      circuit_breaker: false
      exclude_scope_info: false
      exemplar_filter: always_off

events:
  providers:
    nats:
      - id: default
        url: "nats://localhost:4222"
      - id: my-nats
        url: "nats://localhost:4222"
    kafka:
      - id: my-kafka
        brokers:
          - "localhost:9092"
    redis:
      - id: my-redis
        urls:
          - "redis://localhost:6379/2"
