package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachetest/articles/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachetest/articles/subgraph/model"
)

// FindArticleByID is the resolver for the findArticleByID field.
func (r *entityResolver) FindArticleByID(ctx context.Context, id string) (*model.Article, error) {
	return buildArticle(id), nil
}

// FindPersonalizedByID is the resolver for the findPersonalizedByID field.
func (r *entityResolver) FindPersonalizedByID(ctx context.Context, id string) (model.Personalized, error) {
	// The articles subgraph declares Personalized as a plain interface with only the id key.
	// The router never actually fetches _entities(Personalized) from this subgraph (that's the
	// viewer subgraph's @interfaceObject). Returning an Article as the concrete type is a safe stub.
	return buildArticle(id), nil
}

// FindViewerByID is the resolver for the findViewerByID field.
func (r *entityResolver) FindViewerByID(ctx context.Context, id string) (*model.Viewer, error) {
	return &model.Viewer{
		ID: id,
		RecommendedArticles: []*model.Article{
			buildArticle("a1"),
			buildArticle("a2"),
			buildArticle("a3"),
		},
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
