// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Invoice struct {
	ID          string `json:"id"`
	AmountCents int    `json:"amountCents"`
	Paid        bool   `json:"paid"`
}

func (Invoice) IsEntity() {}

type Organization struct {
	ID           string        `json:"id"`
	MemberCount  int           `json:"memberCount"`
	Subscription *Subscription `json:"subscription,omitempty"`
	Invoices     []*Invoice    `json:"invoices"`
}

func (Organization) IsEntity() {}

type Query struct {
}

type Subscription struct {
	ID                string        `json:"id"`
	OrgID             string        `json:"orgId"`
	PlanID            string        `json:"planId"`
	Status            string        `json:"status"`
	InternalLedgerRef string        `json:"internalLedgerRef"`
	SeatUtilization   float64       `json:"seatUtilization"`
	Org               *Organization `json:"org"`
}

func (Subscription) IsEntity() {}
