package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/catalog/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/catalog/subgraph/model"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/deferdemo"
)

// Storefront is the resolver for the storefront field.
func (r *queryResolver) Storefront(ctx context.Context) ([]*model.Product, error) {
	if err := r.Latencies.Wait(ctx, deferdemo.FieldCatalogStorefront); err != nil {
		return nil, err
	}
	return products, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
