// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file wg/cosmo/common/common.proto (package wg.cosmo.common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file wg/cosmo/common/common.proto.
 */
export const file_wg_cosmo_common_common: GenFile = /*@__PURE__*/
  fileDesc("Chx3Zy9jb3Ntby9jb21tb24vY29tbW9uLnByb3RvEg93Zy5jb3Ntby5jb21tb24q9AMKDkVudW1TdGF0dXNDb2RlEgYKAk9LEAASBwoDRVJSEAESEQoNRVJSX05PVF9GT1VORBACEhYKEkVSUl9BTFJFQURZX0VYSVNUUxADEh8KG0VSUl9JTlZBTElEX1NVQkdSQVBIX1NDSEVNQRAEEiMKH0VSUl9TVUJHUkFQSF9DT01QT1NJVElPTl9GQUlMRUQQBRIdChlFUlJfU1VCR1JBUEhfQ0hFQ0tfRkFJTEVEEAYSFgoSRVJSX0lOVkFMSURfTEFCRUxTEAcSGgoWRVJSX0FOQUxZVElDU19ESVNBQkxFRBAIEhsKF0VSUk9SX05PVF9BVVRIRU5USUNBVEVEEAkSFwoTRVJSX09QRU5BSV9ESVNBQkxFRBAKEhoKFkVSUl9GUkVFX1RSSUFMX0VYUElSRUQQCxIYChRFUlJPUl9OT1RfQVVUSE9SSVpFRBAMEhUKEUVSUl9MSU1JVF9SRUFDSEVEEA0SGQoVRVJSX0RFUExPWU1FTlRfRkFJTEVEEA4SFAoQRVJSX0lOVkFMSURfTkFNRRAPEhQKEEVSUl9VUEdSQURFX1BMQU4QEBITCg9FUlJfQkFEX1JFUVVFU1QQERIuCipFUlJfU0NIRU1BX01JU01BVENIX1dJVEhfQVBQUk9WRURfUFJPUE9TQUwQEiqWAQobR3JhcGhRTFN1YnNjcmlwdGlvblByb3RvY29sEiQKIEdSQVBIUUxfU1VCU0NSSVBUSU9OX1BST1RPQ09MX1dTEAASJQohR1JBUEhRTF9TVUJTQ1JJUFRJT05fUFJPVE9DT0xfU1NFEAESKgomR1JBUEhRTF9TVUJTQ1JJUFRJT05fUFJPVE9DT0xfU1NFX1BPU1QQAiqbAQobR3JhcGhRTFdlYnNvY2tldFN1YnByb3RvY29sEiYKIkdSQVBIUUxfV0VCU09DS0VUX1NVQlBST1RPQ09MX0FVVE8QABIkCiBHUkFQSFFMX1dFQlNPQ0tFVF9TVUJQUk9UT0NPTF9XUxABEi4KKkdSQVBIUUxfV0VCU09DS0VUX1NVQlBST1RPQ09MX1RSQU5TUE9SVF9XUxACYgZwcm90bzM");

/**
 * @generated from enum wg.cosmo.common.EnumStatusCode
 */
export enum EnumStatusCode {
  /**
   * @generated from enum value: OK = 0;
   */
  OK = 0,

  /**
   * @generated from enum value: ERR = 1;
   */
  ERR = 1,

  /**
   * @generated from enum value: ERR_NOT_FOUND = 2;
   */
  ERR_NOT_FOUND = 2,

  /**
   * @generated from enum value: ERR_ALREADY_EXISTS = 3;
   */
  ERR_ALREADY_EXISTS = 3,

  /**
   * @generated from enum value: ERR_INVALID_SUBGRAPH_SCHEMA = 4;
   */
  ERR_INVALID_SUBGRAPH_SCHEMA = 4,

  /**
   * @generated from enum value: ERR_SUBGRAPH_COMPOSITION_FAILED = 5;
   */
  ERR_SUBGRAPH_COMPOSITION_FAILED = 5,

  /**
   * @generated from enum value: ERR_SUBGRAPH_CHECK_FAILED = 6;
   */
  ERR_SUBGRAPH_CHECK_FAILED = 6,

  /**
   * @generated from enum value: ERR_INVALID_LABELS = 7;
   */
  ERR_INVALID_LABELS = 7,

  /**
   * @generated from enum value: ERR_ANALYTICS_DISABLED = 8;
   */
  ERR_ANALYTICS_DISABLED = 8,

  /**
   * @generated from enum value: ERROR_NOT_AUTHENTICATED = 9;
   */
  ERROR_NOT_AUTHENTICATED = 9,

  /**
   * @generated from enum value: ERR_OPENAI_DISABLED = 10;
   */
  ERR_OPENAI_DISABLED = 10,

  /**
   * @generated from enum value: ERR_FREE_TRIAL_EXPIRED = 11;
   */
  ERR_FREE_TRIAL_EXPIRED = 11,

  /**
   * @generated from enum value: ERROR_NOT_AUTHORIZED = 12;
   */
  ERROR_NOT_AUTHORIZED = 12,

  /**
   * @generated from enum value: ERR_LIMIT_REACHED = 13;
   */
  ERR_LIMIT_REACHED = 13,

  /**
   * @generated from enum value: ERR_DEPLOYMENT_FAILED = 14;
   */
  ERR_DEPLOYMENT_FAILED = 14,

  /**
   * @generated from enum value: ERR_INVALID_NAME = 15;
   */
  ERR_INVALID_NAME = 15,

  /**
   * @generated from enum value: ERR_UPGRADE_PLAN = 16;
   */
  ERR_UPGRADE_PLAN = 16,

  /**
   * @generated from enum value: ERR_BAD_REQUEST = 17;
   */
  ERR_BAD_REQUEST = 17,

  /**
   * @generated from enum value: ERR_SCHEMA_MISMATCH_WITH_APPROVED_PROPOSAL = 18;
   */
  ERR_SCHEMA_MISMATCH_WITH_APPROVED_PROPOSAL = 18,
}

/**
 * Describes the enum wg.cosmo.common.EnumStatusCode.
 */
export const EnumStatusCodeSchema: GenEnum<EnumStatusCode> = /*@__PURE__*/
  enumDesc(file_wg_cosmo_common_common, 0);

/**
 * @generated from enum wg.cosmo.common.GraphQLSubscriptionProtocol
 */
export enum GraphQLSubscriptionProtocol {
  /**
   * Subscribe with a websocket, automatically negotiating the subprotocol
   *
   * @generated from enum value: GRAPHQL_SUBSCRIPTION_PROTOCOL_WS = 0;
   */
  GRAPHQL_SUBSCRIPTION_PROTOCOL_WS = 0,

  /**
   * Subscribe via SSE with a GET request
   *
   * @generated from enum value: GRAPHQL_SUBSCRIPTION_PROTOCOL_SSE = 1;
   */
  GRAPHQL_SUBSCRIPTION_PROTOCOL_SSE = 1,

  /**
   * Subscribe via SSE with a POST request
   *
   * @generated from enum value: GRAPHQL_SUBSCRIPTION_PROTOCOL_SSE_POST = 2;
   */
  GRAPHQL_SUBSCRIPTION_PROTOCOL_SSE_POST = 2,
}

/**
 * Describes the enum wg.cosmo.common.GraphQLSubscriptionProtocol.
 */
export const GraphQLSubscriptionProtocolSchema: GenEnum<GraphQLSubscriptionProtocol> = /*@__PURE__*/
  enumDesc(file_wg_cosmo_common_common, 1);

/**
 * @generated from enum wg.cosmo.common.GraphQLWebsocketSubprotocol
 */
export enum GraphQLWebsocketSubprotocol {
  /**
   * @generated from enum value: GRAPHQL_WEBSOCKET_SUBPROTOCOL_AUTO = 0;
   */
  GRAPHQL_WEBSOCKET_SUBPROTOCOL_AUTO = 0,

  /**
   * @generated from enum value: GRAPHQL_WEBSOCKET_SUBPROTOCOL_WS = 1;
   */
  GRAPHQL_WEBSOCKET_SUBPROTOCOL_WS = 1,

  /**
   * @generated from enum value: GRAPHQL_WEBSOCKET_SUBPROTOCOL_TRANSPORT_WS = 2;
   */
  GRAPHQL_WEBSOCKET_SUBPROTOCOL_TRANSPORT_WS = 2,
}

/**
 * Describes the enum wg.cosmo.common.GraphQLWebsocketSubprotocol.
 */
export const GraphQLWebsocketSubprotocolSchema: GenEnum<GraphQLWebsocketSubprotocol> = /*@__PURE__*/
  enumDesc(file_wg_cosmo_common_common, 2);

