package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"log"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/mood/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/mood/subgraph/model"
	"github.com/wundergraph/cosmo/router/pkg/pubsub/datasource"
	"github.com/wundergraph/cosmo/router/pkg/pubsub/nats"
)

// publishMoodEvent emits an Employee-updated event for subscription consumers.
// Failures (missing adapter, broker down) are logged but never fail the
// mutation — local storage has already been updated.
func (r *mutationResolver) publishMoodEvent(ctx context.Context, providerID, subject, payload string) {
	adapter := r.NatsPubSubByProviderID[providerID]
	if adapter == nil {
		log.Printf("mood: nats provider %q unavailable, skipping publish to %s", providerID, subject)
		return
	}
	err := adapter.Publish(ctx, &nats.PublishAndRequestEventConfiguration{
		Subject: subject,
	}, []datasource.StreamEvent{&nats.MutableEvent{Data: []byte(payload)}})
	if err != nil {
		log.Printf("mood: nats publish failed via %q to %s: %v", providerID, subject, err)
	}
}

// UpdateMood is the resolver for the updateMood field.
func (r *mutationResolver) UpdateMood(ctx context.Context, employeeID int, mood model.Mood) (*model.Employee, error) {
	storage.Set(employeeID, mood)
	payload := fmt.Sprintf(`{"id":%d,"__typename": "Employee"}`, employeeID)

	r.publishMoodEvent(ctx, "default", r.GetPubSubName(fmt.Sprintf("employeeUpdated.%d", employeeID)), payload)
	r.publishMoodEvent(ctx, "my-nats", r.GetPubSubName(fmt.Sprintf("employeeUpdatedMyNats.%d", employeeID)), payload)

	return &model.Employee{ID: employeeID, CurrentMood: mood}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
