{{ if .Values.global.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "controlplane.fullname" . }}-seed-organization-{{ now | unixEpoch }}"
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
    # Run the job before installing the helm chart
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    # Support for k14s.io. This annotation ensure that the job is run after the postgresql and keycloak deployment
    kapp.k14s.io/change-rule.postgres: "upsert after upserting cosmo.apps.postgresql.wundergraph.com/deployment"
    {{- if .Values.global.keycloak.enabled }}
    kapp.k14s.io/change-rule.keycloak: "upsert after upserting cosmo.apps.keycloak.wundergraph.com/deployment"
    {{- end }}
spec:
  backoffLimit: 10
  parallelism: 1
  ttlSecondsAfterFinished: 360
  template:
    metadata:
      name: "{{ include "controlplane.fullname" . }}-seed-organization"
      labels:
        {{- include "controlplane.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: seed
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "controlplane.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KC_REALM
              valueFrom:
                configMapKeyRef:
                  name: {{ include "controlplane.fullname" . }}-configmap
                  key: keycloakRealm
            - name: KC_LOGIN_REALM
              valueFrom:
                configMapKeyRef:
                  name: {{ include "controlplane.fullname" . }}-configmap
                  key: keycloakLoginRealm
            - name: KC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "controlplane.fullname" . }}-configmap
                  key: keycloakApiUrl
            - name: KC_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}

                  key: keycloakAdminUser
            - name: KC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}

                  key: keycloakAdminPassword
            - name: KC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "controlplane.fullname" . }}-configmap
                  key: keycloakClientId
            - name: API_KEY
              value: "{{ .Values.global.seed.apiKey }}"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}

                  key: databaseUrl
            {{- if .Values.configuration.databaseTlsCert }}
            - name: DB_TLS_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}
                  key: databaseTlsCert
            {{- end }}
            {{- if .Values.configuration.databaseTlsCa }}
            - name: DB_TLS_CA
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}
                  key: databaseTlsCa
            {{- end }}
            {{- if .Values.configuration.databaseTlsKey }}
            - name: DB_TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane.secretName" . }}
                  key: databaseTlsKey
            {{- end }}
            - name: USER_EMAIL
              value: "{{ .Values.global.seed.userEmail }}"
            - name: USER_PASSWORD
              value: "{{ .Values.global.seed.userPassword }}"
            - name: USER_FIRSTNAME
              value: "{{ .Values.global.seed.firstName }}"
            - name: USER_LASTNAME
              value: "{{ .Values.global.seed.lastName }}"
            - name: ORGANIZATION_NAME
              value: "{{ .Values.global.seed.organizationName }}"
            - name: ORGANIZATION_SLUG
              value: "{{ .Values.global.seed.organizationSlug }}"
          args:
            - "/app/dist/bin/seed.js"
{{- end }}