name: "Build and Push Image (PR only)"
description: "This action to build and push docker image for CI in Pull Request only."
inputs:
  github_token:
    description: 'GitHub Token'
    required: true

  skip_dirs:
    description: 'A comma separated list of folders to ignore'
    required: false

  image_ref:
    description: "The name of the container"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Obtain template file
      shell: bash
      run: curl -o trivy-pr-comment.tpl https://raw.githubusercontent.com/domstolene/trivy-pr-report/main/trivy-pr-comment.tpl

    - name: Run Trivy for PR report
      uses: aquasecurity/trivy-action@0.29.0
      id: scan
      with:
        image-ref: ${{ inputs.image_ref }}
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'