// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Publishable interface {
	IsPublishable()
	GetID() string
	GetTitle() string
	GetPublishedAt() string
}

type Article struct {
	ID             string        `json:"id"`
	Title          string        `json:"title"`
	PublishedAt    string        `json:"publishedAt"`
	RelatedContent []Publishable `json:"relatedContent"`
}

func (Article) IsPublishable()              {}
func (this Article) GetID() string          { return this.ID }
func (this Article) GetTitle() string       { return this.Title }
func (this Article) GetPublishedAt() string { return this.PublishedAt }

func (Article) IsEntity() {}

type Podcast struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	PublishedAt string `json:"publishedAt"`
}

func (Podcast) IsPublishable()              {}
func (this Podcast) GetID() string          { return this.ID }
func (this Podcast) GetTitle() string       { return this.Title }
func (this Podcast) GetPublishedAt() string { return this.PublishedAt }

func (Podcast) IsEntity() {}

type Query struct {
}

type User struct {
	ID                  string     `json:"id"`
	DisplayName         string     `json:"displayName"`
	RecommendedArticles []*Article `json:"recommendedArticles"`
}

func (User) IsEntity() {}
