package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/viewer/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/viewer/subgraph/model"
)

// FindPersonalizedByID is the resolver for the findPersonalizedByID field.
func (r *entityResolver) FindPersonalizedByID(ctx context.Context, id string) (*model.Personalized, error) {
	// The @interfaceObject resolver: returns currentViewer for any entity implementing Personalized.
	// The entity's actual type (Article, etc.) doesn't matter — the viewer is from the auth context.
	viewer := viewerFromContext(ctx)
	return &model.Personalized{
		ID:            id,
		CurrentViewer: viewer,
	}, nil
}

// FindViewerByID is the resolver for the findViewerByID field.
func (r *entityResolver) FindViewerByID(ctx context.Context, id string) (*model.Viewer, error) {
	return viewersByID[id], nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
