// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID                         string     `json:"id"`
	CurrentViewer              *Viewer    `json:"currentViewer,omitempty"`
	ViewCount                  int        `json:"viewCount"`
	Rating                     float64    `json:"rating"`
	ReviewSummary              string     `json:"reviewSummary"`
	RelatedArticles            []*Article `json:"relatedArticles"`
	PersonalizedRecommendation string     `json:"personalizedRecommendation"`
}

func (Article) IsEntity() {}

// Extends Catalog with description from a second subgraph (for partial cache load testing)
type Catalog struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	LastUpdated string `json:"lastUpdated"`
}

func (Catalog) IsEntity() {}

type Query struct {
}

type Viewer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Viewer) IsEntity() {}
