import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';
import semver from 'semver';
import { format, resolveConfig } from 'prettier';
import { renderTemplateModule, templateDirNames, templateModuleComment } from '../../scripts/compile-templates.js';
import { GO_TOOL_VERSIONS } from '../../src/commands/router/commands/plugin/toolchain.js';

const templatesDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../src/commands/router/commands/plugin/templates',
);

const goTemplateDir = join(templatesDir, 'go');

function readGoTemplate(name: string): string {
  return readFileSync(join(goTemplateDir, `${name}.template`), 'utf8');
}

// `go 1.27.0` -> `1.27.0`
function goDirectiveVersion(): string {
  const match = /^go\s+(\S+)$/m.exec(readGoTemplate('go.mod'));
  expect(match, 'go.mod.template must declare a go directive').not.toBeNull();
  // A bare `go 1.27` is valid in go.mod but not valid semver, so normalise it
  return semver.coerce(match![1])!.version;
}

// `FROM --platform=$BUILDPLATFORM golang:1.27-alpine AS builder` -> `1.27`
function dockerGoTag(): string {
  const match = /golang:(\d+\.\d+)/.exec(readGoTemplate('Dockerfile'));
  expect(match, 'Dockerfile.template must pin a golang base image').not.toBeNull();
  return match![1];
}

describe('compiled plugin templates', () => {
  // The <folder>.ts modules are generated by `pnpm compile-templates` on prebuild and committed.
  // Nothing else fails if a stale copy is committed, so guard it here.
  test.each(templateDirNames(templatesDir))('%s.ts is up to date with its .template files', async (dirName) => {
    const outFile = join(templatesDir, `${dirName}.ts`);
    const rendered = renderTemplateModule(join(templatesDir, dirName), templateModuleComment(dirName));

    // `pnpm compile-templates` pipes the generated module through prettier before committing it
    const generated = await format(rendered!, {
      ...(await resolveConfig(outFile)),
      filepath: outFile,
    });

    expect(generated, `${dirName}.ts is out of date. Run \`pnpm compile-templates\` and commit the result.`).toBe(
      readFileSync(outFile, 'utf8'),
    );
  });
});

describe('go plugin toolchain version', () => {
  const { range, scriptVersion } = GO_TOOL_VERSIONS.go;

  test('the managed Go toolchain can build the generated go.mod', () => {
    // The toolchain we download for plugin builds must not be older than the go directive
    // we scaffold into the plugin, otherwise `wgc router plugin build` fails on a fresh init.
    expect(semver.gte(scriptVersion, goDirectiveVersion())).toBe(true);
  });

  test('the accepted host Go range cannot admit a version below the generated go.mod', () => {
    // A host Go that satisfies `range` is used as-is instead of downloading scriptVersion,
    // so the lower bound of the range must also be able to build the scaffolded plugin.
    const lowest = semver.minVersion(range);
    expect(lowest, `${range} must have a lower bound`).not.toBeNull();
    expect(semver.gte(lowest!.version, goDirectiveVersion())).toBe(true);
  });

  test('the installed toolchain itself satisfies the accepted range', () => {
    expect(semver.satisfies(scriptVersion, range)).toBe(true);
  });

  test('the Dockerfile base image matches the generated go.mod', () => {
    const goDirective = goDirectiveVersion();
    expect(dockerGoTag()).toBe(`${semver.major(goDirective)}.${semver.minor(goDirective)}`);
  });
});
