/**
 * Assemble the .coderabbit.yaml from generated guidelines, path instructions,
 * and reviewer profiles.
 *
 * Reads output/guidelines.md, output/path_instructions.json, output/reviewer_profiles.json
 * Writes ../.coderabbit.yaml (repo root)
 *
 * Usage: bun run scripts/build-coderabbit.ts [--output PATH]
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const OUTPUT_DIR = join(import.meta.dir, "../output");
const GUIDELINES_FILE = join(OUTPUT_DIR, "guidelines.md");
const PATH_INSTRUCTIONS_FILE = join(OUTPUT_DIR, "path_instructions.json");
const PROFILES_FILE = join(OUTPUT_DIR, "reviewer_profiles.json");
const ANTI_PATTERNS_JSON = join(OUTPUT_DIR, "anti_patterns.json");
const DEFAULT_OUTPUT = join(import.meta.dir, "../../.coderabbit.yaml");

interface ReviewerProfile {
  total_comments: number;
  subsystems: Record<string, number>;
  file_types: Record<string, number>;
  avg_comment_length: number;
  prs_reviewed: number;
}

// Minimum comments in a subsystem to be considered an expert
const EXPERT_THRESHOLD = 20;

function getExpertsForSubsystem(
  profiles: Record<string, ReviewerProfile>,
  subsystem: string,
): { username: string; comments: number }[] {
  const experts: { username: string; comments: number }[] = [];

  for (const [username, profile] of Object.entries(profiles)) {
    const count = profile.subsystems[subsystem] ?? 0;
    if (count >= EXPERT_THRESHOLD) {
      experts.push({ username, comments: count });
    }
  }

  return experts.sort((a, b) => b.comments - a.comments);
}

async function main() {
  const args = process.argv.slice(2);
  const outputIdx = args.indexOf("--output");
  const outputPath = outputIdx !== -1 ? args[outputIdx + 1] : DEFAULT_OUTPUT;

  const guidelines = await readFile(GUIDELINES_FILE, "utf-8");
  const pathInstructionsRaw = await readFile(PATH_INSTRUCTIONS_FILE, "utf-8");
  const pathInstructions: Record<string, { path: string; instructions: string }> =
    JSON.parse(pathInstructionsRaw);

  let profiles: Record<string, ReviewerProfile> = {};
  try {
    profiles = JSON.parse(await readFile(PROFILES_FILE, "utf-8"));
  } catch {
    console.log("No reviewer profiles found, skipping expert tagging");
  }

  interface ClassifiedThread {
    pr_number: number;
    file: string;
    bot_comment: string;
    human_replies: { user: string; body: string }[];
    outcome: string;
  }

  let antiPatterns: ClassifiedThread[] = [];
  try {
    antiPatterns = JSON.parse(await readFile(ANTI_PATTERNS_JSON, "utf-8"));
  } catch {
    console.log("No anti-patterns found, skipping false positive guidance");
  }

  const lines: string[] = [];

  lines.push("# Auto-generated by codereview pipeline from team review history");
  lines.push("# See codereview/STRATEGY.md for details");
  lines.push("");
  lines.push("language: en-US");
  lines.push("");
  lines.push("reviews:");
  lines.push("  collapse_walkthrough: true");
  lines.push("  poem: false");
  lines.push("  high_level_summary: true");
  lines.push("  auto_review:");
  lines.push("    enabled: true");

  // Exclude codereview pipeline from reviews
  lines.push("  path_filters:");
  lines.push('    - "!codereview/**"');
  lines.push("");

  // Global instructions
  lines.push("  instructions: |");
  for (const line of guidelines.split("\n")) {
    lines.push(line.trim() ? "    " + line : "");
  }

  // Add anti-pattern guidance from false positive analysis
  const rejected = antiPatterns.filter((t) => t.outcome === "rejected");
  if (rejected.length > 0) {
    lines.push("");
    lines.push("    ## Known False Positive Patterns");
    lines.push("");
    lines.push("    The following patterns were previously flagged but explicitly rejected by human reviewers.");
    lines.push("    Do NOT flag these unless the context is clearly different from the original case.");
    lines.push("");
    for (const t of rejected) {
      const replySnippet = t.human_replies[0]?.body.slice(0, 150).replace(/\n/g, " ") ?? "";
      const botSnippet = t.bot_comment
        .replace(/^_[^_]+_\s*(\|\s*_[^_]+_\s*)?/gm, "")
        .replace(/<details>[\s\S]*?<\/details>/g, "")
        .replace(/<[^>]+>/g, "")
        .trim()
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l.length > 10 && !l.startsWith("🧩") && !l.startsWith("🌐") && !l.startsWith("🏁") && !l.startsWith("💡"))
        [0]
        ?.replace(/^\*\*/, "")
        .replace(/\*\*$/, "")
        .replace(/\*\*/g, "")
        .slice(0, 120) ?? "";
      if (botSnippet) {
        lines.push(`    - "${botSnippet}" — rejected: "${replySnippet}" (#${t.pr_number})`);
      }
    }
  }

  lines.push("");

  // Path instructions with expert tagging
  if (Object.keys(pathInstructions).length > 0) {
    lines.push("  path_instructions:");

    for (const [subsystem, { path, instructions }] of Object.entries(pathInstructions)) {
      lines.push(`    - path: "${path}"`);
      lines.push("      instructions: |");

      for (const line of instructions.split("\n")) {
        lines.push(line.trim() ? "        " + line : "");
      }

      // Add expert escalation instructions
      const experts = getExpertsForSubsystem(profiles, subsystem);
      if (experts.length > 0) {
        lines.push("");
        lines.push("        ## Expert Escalation");
        lines.push("        When you detect a complex or architecturally significant change in this subsystem,");
        lines.push("        add a comment tagging the relevant domain expert(s) for human review.");
        lines.push("        Triggers for escalation:");
        lines.push("        - Changes to core abstractions, interfaces, or module boundaries");
        lines.push("        - Performance-sensitive code paths (hot loops, allocations, concurrency)");
        lines.push("        - Breaking changes to public APIs or configuration schema");
        lines.push("        - Security-relevant changes (auth, validation, input handling)");
        lines.push(`        Domain experts for ${subsystem}:`);
        for (const expert of experts.slice(0, 3)) {
          lines.push(`        - @${expert.username} (${expert.comments} review comments in ${subsystem})`);
        }
        lines.push('        Format: "**Expert review recommended**: @username - [brief reason]"');
      }

      lines.push("");
    }
  }

  const yaml = lines.join("\n") + "\n";
  await writeFile(outputPath, yaml);
  console.log(`Wrote .coderabbit.yaml to ${outputPath}`);
  console.log(`  Global instructions: ${guidelines.split("\n").length} lines`);
  console.log(`  Path instructions: ${Object.keys(pathInstructions).length} subsystems`);

  // Report experts
  for (const [subsystem] of Object.entries(pathInstructions)) {
    const experts = getExpertsForSubsystem(profiles, subsystem);
    if (experts.length > 0) {
      console.log(`  ${subsystem} experts: ${experts.map((e) => `${e.username}(${e.comments})`).join(", ")}`);
    }
  }
}

main().catch(console.error);
