apiVersion: v1
kind: Service
metadata:
  name: {{ include "router.fullname" . }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.configuration.prometheus.enabled }}
    - port: {{ .Values.configuration.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "router.selectorLabels" . | nindent 4 }}
