// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ContentItem interface {
	IsEntity()
	IsContentItem()
	GetID() string
}

type Publishable interface {
	IsPublishable()
	GetID() string
	GetTitle() string
	GetPublishedAt() string
}

type SearchResult interface {
	IsSearchResult()
}

type Article struct {
	ID           string `json:"id"`
	Slug         string `json:"slug"`
	Locale       string `json:"locale"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	WordCount    int    `json:"wordCount"`
	PublishedAt  string `json:"publishedAt"`
	HeroImageURL string `json:"heroImageUrl"`
	Author       *User  `json:"author"`
}

func (Article) IsSearchResult() {}

func (Article) IsPublishable()              {}
func (this Article) GetID() string          { return this.ID }
func (this Article) GetTitle() string       { return this.Title }
func (this Article) GetPublishedAt() string { return this.PublishedAt }

func (Article) IsContentItem() {}

func (Article) IsEntity() {}

type Podcast struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	PublishedAt     string `json:"publishedAt"`
	DurationSeconds int    `json:"durationSeconds"`
	Host            *User  `json:"host"`
}

func (Podcast) IsSearchResult() {}

func (Podcast) IsPublishable()              {}
func (this Podcast) GetID() string          { return this.ID }
func (this Podcast) GetTitle() string       { return this.Title }
func (this Podcast) GetPublishedAt() string { return this.PublishedAt }

func (Podcast) IsContentItem() {}

func (Podcast) IsEntity() {}

type Query struct {
}

type User struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
}

func (User) IsEntity() {}
