name: 'Setup Go'
description: 'This action install go and cache modules and build dependencies'
inputs:
  go-version:
    description: 'The go version to install'
    default: '1.25'
    required: false
  cache-dependency-path:
    description: 'The path to the dependency to cache'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
