---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otelcollector.fullname" . }}
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the secret changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "otelcollector.labels" . | nindent 4 }}
stringData:
  clickhouseDsn: "{{ .Values.configuration.clickhouseDsn }}"
  promUsername: "{{ .Values.configuration.promUsername }}"
  promPassword: "{{ .Values.configuration.promPassword }}"
  authJwtSecret: "{{ .Values.global.controlplane.jwtSecret }}"
  promRemoteWriteEndpoint: "{{ .Values.configuration.promWriteEndpoint }}"