apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelcollector.fullname" . }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "otelcollector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 13133
      targetPort: healthcheck
      protocol: TCP
      name: healthcheck
    {{- if and .Values.configuration.prometheus.enabled (not (eq .Values.configuration.prometheus.level "none")) }}
    - port: {{ .Values.configuration.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "otelcollector.selectorLabels" . | nindent 4 }}
