package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/wundergraph/cosmo/terraform-provider-cosmo/internal/api"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &FederatedGraphDataSource{}

func NewFederatedGraphDataSource() datasource.DataSource {
	return &FederatedGraphDataSource{}
}

// FederatedGraphDataSource defines the data source implementation.
type FederatedGraphDataSource struct {
	provider Provider
}

// FederatedGraphDataSourceModel describes the data source data model.
type FederatedGraphDataSourceModel struct {
	Id                     types.String `tfsdk:"id"`
	Name                   types.String `tfsdk:"name"`
	Namespace              types.String `tfsdk:"namespace"`
	Readme                 types.String `tfsdk:"readme"`
	ServiceUrl             types.String `tfsdk:"service_url"`
	AdmissionWebhookUrl    types.String `tfsdk:"admission_webhook_url"`
	AdmissionWebhookSecret types.String `tfsdk:"admission_webhook_secret"`
	LabelMatchers          types.List   `tfsdk:"label_matchers"`
}

func (d *FederatedGraphDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_federated_graph"
}

func (d *FederatedGraphDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Cosmo Federated Graph Data Source",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier of the federated graph resource, automatically generated by the system.",
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the federated graph.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "The namespace in which the federated graph is located.",
				Optional:            true,
			},
			"readme": schema.StringAttribute{
				MarkdownDescription: "Readme content for the federated graph.",
				Optional:            true,
			},
			"admission_webhook_url": schema.StringAttribute{
				MarkdownDescription: "The URL for the admission webhook that will be triggered during graph operations.",
				Optional:            true,
			},
			"admission_webhook_secret": schema.StringAttribute{
				MarkdownDescription: "The secret token used to authenticate the admission webhook requests.",
				Optional:            true,
				Sensitive:           true,
			},
			"service_url": schema.StringAttribute{
				MarkdownDescription: "The URL of the service that routes requests to the federated graph.",
				Optional:            true,
			},
			"label_matchers": schema.ListAttribute{
				MarkdownDescription: "A list of label matchers used to select the services that will form the federated graph.",
				Optional:            true,
				ElementType:         types.StringType,
			},
		},
	}
}

func (d *FederatedGraphDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*Provider)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *http.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.provider = *provider
}

func (d *FederatedGraphDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data FederatedGraphDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Validate that the name is set
	if data.Name.IsNull() || data.Name.ValueString() == "" {
		resp.Diagnostics.AddError(
			"Invalid Federated Graph Name",
			"The 'name' attribute is required.",
		)
		return
	}

	// Default namespace if not provided
	namespace := data.Namespace.ValueString()
	if namespace == "" {
		namespace = "default"
	}

	// Fetch the federated graph via the API
	apiResponse, err := api.GetFederatedGraph(ctx, d.provider.client, d.provider.cosmoApiKey, data.Name.ValueString(), namespace)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Federated Graph",
			fmt.Sprintf("Could not read federated graph: %s", err),
		)
		return
	}

	// Update state with the fetched data
	graph := apiResponse.Graph
	data.Name = types.StringValue(graph.Name)
	data.Namespace = types.StringValue(graph.Namespace)
	data.ServiceUrl = types.StringValue(graph.RoutingURL)

	// Handle Readme pointer safely
	if graph.Readme != nil {
		data.Readme = types.StringValue(*graph.Readme)
	} else {
		data.Readme = types.StringNull()
	}

	// Handle AdmissionWebhookURL pointer safely
	if graph.AdmissionWebhookUrl != nil {
		data.AdmissionWebhookUrl = types.StringValue(*graph.AdmissionWebhookUrl)
	} else {
		data.AdmissionWebhookUrl = types.StringNull()
	}

	var labelMatchers []attr.Value
	for _, matcher := range graph.LabelMatchers {
		labelMatchers = append(labelMatchers, types.StringValue(matcher))
	}
	data.LabelMatchers = types.ListValueMust(types.StringType, labelMatchers)

	tflog.Trace(ctx, "Read federated graph data source", map[string]interface{}{
		"id": data.Id.ValueString(),
	})

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
