package provider

import (
	"context"
	"fmt"

	"connectrpc.com/connect"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/wundergraph/cosmo/terraform-provider-cosmo/gen/proto/wg/cosmo/common"
	platform "github.com/wundergraph/cosmo/terraform-provider-cosmo/gen/proto/wg/cosmo/platform/v1"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &FederatedGraphResource{}
var _ resource.ResourceWithImportState = &FederatedGraphResource{}

func NewFederatedGraphResource() resource.Resource {
	return &FederatedGraphResource{}
}

// FederatedGraphResource defines the resource implementation for federated graphs.
type FederatedGraphResource struct {
	provider Provider
}

// FederatedGraphResourceModel describes the resource data model for a federated graph.
type FederatedGraphResourceModel struct {
	Id                     types.String `tfsdk:"id"`
	Name                   types.String `tfsdk:"name"`
	Namespace              types.String `tfsdk:"namespace"`
	Readme                 types.String `tfsdk:"readme"`
	ServiceUrl             types.String `tfsdk:"service_url"`
	AdmissionWebhookURL    types.String `tfsdk:"admission_webhook_url"`
	AdmissionWebhookSecret types.String `tfsdk:"admission_webhook_secret"`
	LabelMatchers          types.List   `tfsdk:"label_matchers"`
}

func (r *FederatedGraphResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_federated_graph"
}

func (r *FederatedGraphResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Federated Graph Resource for managing federated graphs",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier of the federated graph resource, automatically generated by the system.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the federated graph. This is used to identify the graph and must be unique within the namespace.",
				Optional:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "The namespace in which the federated graph is located. Defaults to 'default' if not provided.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("default"),
			},
			"readme": schema.StringAttribute{
				MarkdownDescription: "Readme content for the federated graph.",
				Optional:            true,
			},
			"admission_webhook_url": schema.StringAttribute{
				MarkdownDescription: "The URL for the admission webhook that will be triggered during graph operations.",
				Optional:            true,
			},
			"admission_webhook_secret": schema.StringAttribute{
				MarkdownDescription: "The secret token used to authenticate the admission webhook requests.",
				Optional:            true,
				Sensitive:           true,
			},
			"service_url": schema.StringAttribute{
				MarkdownDescription: "The URL of the service that routes requests to the federated graph. Defaults to 'https://default-service-url.com' if not provided.",
				Required:            true,
			},
			"label_matchers": schema.ListAttribute{
				MarkdownDescription: "A list of label matchers used to select the services that will form the federated graph.",
				Optional:            true,
				ElementType:         types.StringType,
				Computed:            true,
				Default:             listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})),
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *FederatedGraphResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*Provider)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *http.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.provider = *provider
}

func (r *FederatedGraphResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data FederatedGraphResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Name.IsNull() || data.Name.ValueString() == "" {
		resp.Diagnostics.AddError(
			"Invalid Federated Subgraph Name",
			"The 'name' attribute is required.",
		)
		return
	}

	labelMatchers, err := convertLabelMatchers(data.LabelMatchers)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid Federated Subgraph Name",
			"The 'name' attribute is required.",
		)
		return
	}
	
	request := connect.NewRequest(&platform.CreateFederatedGraphRequest{
		Name:                   data.Name.ValueString(),
		RoutingUrl:             data.ServiceUrl.ValueString(),
		Namespace:              data.Namespace.ValueString(),
		AdmissionWebhookURL:    data.AdmissionWebhookURL.ValueString(),
		AdmissionWebhookSecret: data.AdmissionWebhookSecret.ValueStringPointer(),
		Readme:                 data.Readme.ValueStringPointer(),
		LabelMatchers:          labelMatchers,
	})

	request.Header().Set("Authorization", fmt.Sprintf("Bearer %s", r.provider.cosmoApiKey))
	response, err := r.provider.client.CreateFederatedGraph(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating federated subgraph",
			fmt.Sprintf("Could not create federated subgraph: %s", err),
		)
		return
	}

	if response.Msg.GetResponse().Code != common.EnumStatusCode_OK {
		resp.Diagnostics.AddError(
			"Error creating federated subgraph",
			fmt.Sprintf("Creation failed with status code: %v, details: %s", response.Msg.GetResponse().Code, response.Msg.GetResponse().GetDetails()),
		)
		return
	}

	if len(response.Msg.CompositionErrors) > 0 {
		resp.Diagnostics.AddError(
			"Composition Error",
			fmt.Sprintf("Composition errors: %v", response.Msg.CompositionErrors),
		)
		return
	}
	data.Id = types.StringValue(fmt.Sprintf("%s/%s", data.Namespace.ValueString(), data.Name.ValueString()))

	tflog.Trace(ctx, "created a federated graph resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *FederatedGraphResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data FederatedGraphResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsNull() || data.Id.ValueString() == "" {
		resp.Diagnostics.AddError(
			"Invalid Resource ID",
			"Cannot read federated graph without an ID.",
		)
		return
	}

	request := connect.NewRequest(&platform.GetFederatedGraphByNameRequest{
		Name:      data.Name.ValueString(),
		Namespace: data.Namespace.ValueString(),
	})

	request.Header().Set("Authorization", fmt.Sprintf("Bearer %s", r.provider.cosmoApiKey))

	response, err := r.provider.client.GetFederatedGraphByName(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading federated graph",
			fmt.Sprintf("Could not read federated graph: %s", err),
		)
		return
	}

	if response.Msg.GetResponse().Code != common.EnumStatusCode_OK {
		resp.Diagnostics.AddError(
			"Error reading federated graph",
			fmt.Sprintf("Failed to retrieve federated graph with status code: %v", response.Msg.GetResponse().Code),
		)
		return
	}

	graph := response.Msg.Graph
	data.Name = types.StringValue(graph.Name)
	data.Namespace = types.StringValue(graph.Namespace)
	data.ServiceUrl = types.StringValue(graph.RoutingURL)

	var labelMatchers []attr.Value
	for _, matcher := range graph.LabelMatchers {
		labelMatchers = append(labelMatchers, attr.Value(types.StringValue(matcher)))
	}
	data.LabelMatchers = types.ListValueMust(types.StringType, labelMatchers)

	tflog.Trace(ctx, "read a federated graph resource", map[string]interface{}{
		"id": data.Id.ValueString(),
	})

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *FederatedGraphResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data FederatedGraphResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsNull() || data.Id.ValueString() == "" {
		resp.Diagnostics.AddError(
			"Invalid Resource ID",
			"Cannot update federated graph because the resource ID is missing.",
		)
		return
	}

	labelMatchers, err := convertLabelMatchers(data.LabelMatchers)
	request := connect.NewRequest(&platform.UpdateFederatedGraphRequest{
		Name:                   data.Name.ValueString(),
		RoutingUrl:             data.ServiceUrl.ValueString(),
		LabelMatchers:          labelMatchers,
		Namespace:              data.Namespace.ValueString(),
		AdmissionWebhookURL:    data.AdmissionWebhookURL.ValueStringPointer(),
		AdmissionWebhookSecret: data.AdmissionWebhookSecret.ValueStringPointer(),
	})

	request.Header().Set("Authorization", fmt.Sprintf("Bearer %s", r.provider.cosmoApiKey))
	response, err := r.provider.client.UpdateFederatedGraph(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating federated graph",
			fmt.Sprintf("Could not update federated graph: %s", err),
		)
		return
	}

	if response.Msg.GetResponse().Code != common.EnumStatusCode_OK {
		resp.Diagnostics.AddError(
			"Error updating federated graph",
			fmt.Sprintf("Update failed with status code: %v, details: %s", response.Msg.GetResponse().Code, response.Msg.GetResponse()),
		)
		return
	}

	if len(response.Msg.CompositionErrors) > 0 {
		resp.Diagnostics.AddError(
			"Composition Error",
			fmt.Sprintf("Composition errors: %v", response.Msg.CompositionErrors),
		)
		return
	}

	tflog.Trace(ctx, "updated a federated graph resource", map[string]interface{}{
		"id": data.Id.ValueString(),
	})

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *FederatedGraphResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data FederatedGraphResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if data.Id.IsNull() || data.Id.ValueString() == "" {
		resp.Diagnostics.AddError(
			"Invalid Resource ID",
			"Cannot delete the federated subgraph because the resource ID is missing.",
		)
		return
	}
	request := connect.NewRequest(&platform.DeleteFederatedGraphRequest{
		Name:      data.Name.ValueString(),
		Namespace: data.Namespace.ValueString(),
	})

	request.Header().Set("Authorization", fmt.Sprintf("Bearer %s", ""))

	_, err := r.provider.client.DeleteFederatedGraph(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting federated subgraph",
			fmt.Sprintf("Could not delete federated subgraph with ID %s: %s", data.Id.ValueString(), err),
		)
		return
	}

	tflog.Trace(ctx, "deleted a federated graph resource")
}

func (r *FederatedGraphResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import the federated graph based on the ID
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
