package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/items/subgraph/generated"
	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/items/subgraph/model"
)

// FindItemByID is the resolver for the findItemByID field.
func (r *entityResolver) FindItemByID(ctx context.Context, id string) (*model.Item, error) {
	for _, item := range Items {
		if item.ID == id {
			return item, nil
		}
	}
	return nil, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
