package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/items/subgraph/generated"
	"github.com/wundergraph/cosmo/router-tests/entity_caching/subgraphs/items/subgraph/model"
)

// UpdateItem is the resolver for the updateItem field.
// It persists the new name to the per-resolver store and publishes the
// updated entity on the itemUpdated subscription channel so subscription-based
// @cacheInvalidate flows can be exercised end-to-end in tests.
func (r *mutationResolver) UpdateItem(ctx context.Context, id string, name string) (*model.Item, error) {
	updated, ok := r.Store.update(id, name)
	if !ok {
		return nil, fmt.Errorf("item %s not found", id)
	}
	if r.ItemUpdatedCh != nil {
		select {
		case r.ItemUpdatedCh <- updated:
		default:
		}
	}
	return updated, nil
}

// DeleteItem is the resolver for the deleteItem field.
// It removes the item from the per-resolver store and publishes the deleted
// entity on the itemUpdated subscription channel so tests can verify the
// downstream cache-invalidate pipeline.
func (r *mutationResolver) DeleteItem(ctx context.Context, id string) (*model.Item, error) {
	deleted, ok := r.Store.delete(id)
	if !ok {
		return nil, fmt.Errorf("item %s not found", id)
	}
	if r.ItemUpdatedCh != nil {
		select {
		case r.ItemUpdatedCh <- deleted:
		default:
		}
	}
	return deleted, nil
}

// CreateItem is the resolver for the createItem field.
// It persists the new item to the per-resolver store and publishes it on the
// itemCreated subscription channel so @cachePopulate subscription flows get a
// real event to populate the cache from.
func (r *mutationResolver) CreateItem(ctx context.Context, name string, category string) (*model.Item, error) {
	created := r.Store.create(name, category)
	if r.ItemCreatedCh != nil {
		select {
		case r.ItemCreatedCh <- created:
		default:
		}
	}
	return created, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
// Returns the matching Product without removing it from the in-memory data, so
// tests can verify @cacheInvalidate clears the cache without simulating durable
// deletion in the subgraph.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string, region string) (*model.Product, error) {
	for _, p := range Products {
		if p.ID == id && p.Region == region {
			return p, nil
		}
	}
	return nil, fmt.Errorf("product %s/%s not found", id, region)
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (*model.Item, error) {
	return r.Store.find(id), nil
}

// ItemByPid is the resolver for the itemByPid field.
func (r *queryResolver) ItemByPid(ctx context.Context, pid string) (*model.Item, error) {
	return r.Store.find(pid), nil
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context) ([]*model.Item, error) {
	return r.Store.all(), nil
}

// ItemsByIds is the resolver for the itemsByIds field.
func (r *queryResolver) ItemsByIds(ctx context.Context, ids []string) ([]*model.Item, error) {
	return r.Store.byIDs(ids), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string, region string) (*model.Product, error) {
	for _, p := range Products {
		if p.ID == id && p.Region == region {
			return p, nil
		}
	}
	return nil, nil
}

// ProductBySku is the resolver for the productBySku field.
func (r *queryResolver) ProductBySku(ctx context.Context, sku string) (*model.Product, error) {
	for _, p := range Products {
		if p.Sku == sku {
			return p, nil
		}
	}
	return nil, nil
}

// ProductByName is the resolver for the productByName field.
func (r *queryResolver) ProductByName(ctx context.Context, name string) (*model.Product, error) {
	for _, p := range Products {
		if p.Name == name {
			return p, nil
		}
	}
	return nil, nil
}

// ProductByKey is the resolver for the productByKey field.
func (r *queryResolver) ProductByKey(ctx context.Context, key model.ProductKeyInput) (*model.Product, error) {
	for _, p := range Products {
		if p.ID == key.ID && p.Region == key.Region {
			return p, nil
		}
	}
	return nil, nil
}

// Warehouse is the resolver for the warehouse field.
func (r *queryResolver) Warehouse(ctx context.Context, locationID string) (*model.Warehouse, error) {
	for _, w := range Warehouses {
		if w.Location.ID == locationID {
			return w, nil
		}
	}
	return nil, nil
}

// WarehouseByInput is the resolver for the warehouseByInput field.
func (r *queryResolver) WarehouseByInput(ctx context.Context, input model.WarehouseLocationInput) (*model.Warehouse, error) {
	for _, w := range Warehouses {
		if w.Location.ID == input.Location.ID {
			return w, nil
		}
	}
	return nil, nil
}

// ItemUpdated is the resolver for the itemUpdated field.
func (r *subscriptionResolver) ItemUpdated(ctx context.Context) (<-chan *model.Item, error) {
	return r.ItemUpdatedCh, nil
}

// ItemCreated is the resolver for the itemCreated field.
func (r *subscriptionResolver) ItemCreated(ctx context.Context) (<-chan *model.Item, error) {
	return r.ItemCreatedCh, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
