package core

import (
	"net/http"

	"github.com/go-chi/chi/v5/middleware"
)

var (
	_ EnginePreOriginHandler = (*ForwardRequestIDHeader)(nil)
)

type ForwardRequestIDHeader struct {
}

// This handler will allow to forward request id by overriding request id header in original request
// even if this has been generated in router via http middleware.
func NewForwardRequestIDHeader() *ForwardRequestIDHeader {
	return &ForwardRequestIDHeader{}
}

func (h *ForwardRequestIDHeader) OnOriginRequest(request *http.Request, ctx RequestContext) (*http.Request, *http.Response) {
	// Get request id
	reqID := middleware.GetReqID(ctx.Request().Context())

	// Save it in request header
	// Note: if it wasn't generated by middleware, it will override with the same value
	// Note: so nothing important is made in this case
	ctx.Request().Header.Set(middleware.RequestIDHeader, reqID)

	// Next
	return request, nil
}
