apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "studio.fullname" . }}
  annotations:
    # Support for k14s.io. This annotation will form a group to coordinate deployments with kapp.
    kapp.k14s.io/change-group: "cosmo.apps.studio.wundergraph.com/deployment"
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Roll deployments when this config changes. Name doesn't matter, just needs to be unique.
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "studio.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_COSMO_CP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "studio.fullname" . }}
                  key: controlplaneWebUrl
            - name: NEXT_PUBLIC_COSMO_STUDIO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "studio.fullname" . }}
                  key: studioWebUrl
            - name: NEXT_PUBLIC_SLACK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "studio.fullname" . }}
                  key: slackClientId
            - name: CUSTOM_HEAD_SCRIPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "studio.fullname" . }}
                  key: customHeadScripts
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "studio.fullname" . }}
                  key: stripePublishableKey
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{ with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}

