// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string    `json:"id"`
	WordCount int       `json:"wordCount"`
	Reviews   []*Review `json:"reviews"`
}

func (Article) IsEntity() {}

type Podcast struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (Podcast) IsEntity() {}

type Query struct {
}

type Review struct {
	ID                  string   `json:"id"`
	Rating              int      `json:"rating"`
	Body                string   `json:"body"`
	Author              *User    `json:"author"`
	Article             *Article `json:"article"`
	ReadingTimeAdjusted int      `json:"readingTimeAdjusted"`
}

func (Review) IsEntity() {}

type User struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"displayName"`
	Reviews     []*Review `json:"reviews"`
}

func (User) IsEntity() {}
