package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/demo/pkg/injector"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachegraph/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachegraph/subgraph/model"
)

// userProfileIDByAuthorizationToken maps the demo Authorization bearer tokens to
// user ids. Used by the UserProfile resolver to vary its response per caller so
// that @openfed__queryCache(includeHeaders: true) has a detectable signal.
var userProfileIDByAuthorizationToken = map[string]string{
	"Bearer token-alice":   "u1",
	"Bearer token-bob":     "u2",
	"Bearer token-charlie": "u3",
}

// UpdateArticle is the resolver for the updateArticle field.
func (r *mutationResolver) UpdateArticle(ctx context.Context, id string, title string) (*model.Article, error) {
	return r.articles.update(id, title), nil
}

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, title string, body string, authorName string) (*model.Article, error) {
	return r.articles.create(title, body, authorName), nil
}

// DeleteListing is the resolver for the deleteListing field.
func (r *mutationResolver) DeleteListing(ctx context.Context, key model.ListingKey) (*model.Listing, error) {
	return r.listings.delete(key.SellerID, key.Sku), nil
}

// Article is the resolver for the article field.
func (r *queryResolver) Article(ctx context.Context, id string) (*model.Article, error) {
	return r.articles.find(id), nil
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context) ([]*model.Article, error) {
	return r.articles.all(), nil
}

// ArticlesByIds is the resolver for the articlesByIds field.
func (r *queryResolver) ArticlesByIds(ctx context.Context, ids []string) ([]*model.Article, error) {
	return r.articles.byIDs(ids), nil
}

// ArticleBySlug is the resolver for the articleBySlug field.
func (r *queryResolver) ArticleBySlug(ctx context.Context, slug string) (*model.Article, error) {
	return r.articles.findBySlug(slug), nil
}

// Listing is the resolver for the listing field.
func (r *queryResolver) Listing(ctx context.Context, key model.ListingKey) (*model.Listing, error) {
	return r.listings.get(key.SellerID, key.Sku), nil
}

// Listings is the resolver for the listings field.
func (r *queryResolver) Listings(ctx context.Context) ([]*model.Listing, error) {
	return r.listings.all(), nil
}

// Venue is the resolver for the venue field.
func (r *queryResolver) Venue(ctx context.Context, location model.VenueLocationKey) (*model.Venue, error) {
	return venuesData[location.Address.ID], nil
}

// Venues is the resolver for the venues field.
func (r *queryResolver) Venues(ctx context.Context) ([]*model.Venue, error) {
	return allVenues(), nil
}

// UserProfile is the resolver for the userProfile field.
// The schema declares @openfed__queryCache(includeHeaders: true) so the cache
// key varies by Authorization header. Mirror that on the response side: when a
// known bearer token is present, return that viewer's profile rather than the
// id-based lookup. Without this, different headers would produce identical
// responses and the cache-explorer + benchmark suites could not detect a
// header-variance regression.
func (r *queryResolver) UserProfile(ctx context.Context, id string) (*model.UserProfile, error) {
	if hdr := injector.Header(ctx); hdr != nil {
		if viewerID, ok := userProfileIDByAuthorizationToken[hdr.Get("Authorization")]; ok {
			return userProfilesData[viewerID], nil
		}
	}
	return userProfilesData[id], nil
}

// Catalog is the resolver for the catalog field.
func (r *queryResolver) Catalog(ctx context.Context, id string) (*model.Catalog, error) {
	return catalogsData[id], nil
}

// Catalogs is the resolver for the catalogs field.
func (r *queryResolver) Catalogs(ctx context.Context) ([]*model.Catalog, error) {
	return allCatalogs(), nil
}

// Metric is the resolver for the metric field.
func (r *queryResolver) Metric(ctx context.Context, id string) (*model.Metric, error) {
	return metricsData[id], nil
}

// RecommendedArticles is the resolver for the recommendedArticles field.
func (r *viewerResolver) RecommendedArticles(ctx context.Context, obj *model.Viewer) ([]*model.Article, error) {
	return r.articles.recommendedForViewer(obj.ID), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Viewer returns generated.ViewerResolver implementation.
func (r *Resolver) Viewer() generated.ViewerResolver { return &viewerResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type viewerResolver struct{ *Resolver }
