// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string   `json:"id"`
	Description string   `json:"description"`
	Rating      float64  `json:"rating"`
	Tags        []string `json:"tags"`
}

func (Item) IsEntity() {}

type Location struct {
	ID string `json:"id"`
}

type Product struct {
	ID     string `json:"id"`
	Region string `json:"region"`
	Info   string `json:"info"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Warehouse struct {
	Location *Location `json:"location"`
	Capacity int       `json:"capacity"`
}

func (Warehouse) IsEntity() {}
