// https://protobuf.dev/programming-guides/style/

// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts,import_extension=js"
// @generated from file wg/cosmo/platform/v1/platform.proto (package wg.cosmo.platform.v1, syntax proto3)
/* eslint-disable */

import { PlatformService } from "./platform_pb.js";

/**
 * PlaygroundScripts
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreatePlaygroundScript
 */
export const createPlaygroundScript = PlatformService.method.createPlaygroundScript;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeletePlaygroundScript
 */
export const deletePlaygroundScript = PlatformService.method.deletePlaygroundScript;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdatePlaygroundScript
 */
export const updatePlaygroundScript = PlatformService.method.updatePlaygroundScript;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetPlaygroundScripts
 */
export const getPlaygroundScripts = PlatformService.method.getPlaygroundScripts;

/**
 * Namespaces
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateNamespace
 */
export const createNamespace = PlatformService.method.createNamespace;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteNamespace
 */
export const deleteNamespace = PlatformService.method.deleteNamespace;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RenameNamespace
 */
export const renameNamespace = PlatformService.method.renameNamespace;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespaces
 */
export const getNamespaces = PlatformService.method.getNamespaces;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespace
 */
export const getNamespace = PlatformService.method.getNamespace;

/**
 * Workspace
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetWorkspace
 */
export const getWorkspace = PlatformService.method.getWorkspace;

/**
 * Contracts
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateContract
 */
export const createContract = PlatformService.method.createContract;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateContract
 */
export const updateContract = PlatformService.method.updateContract;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.MoveFederatedGraph
 */
export const moveFederatedGraph = PlatformService.method.moveFederatedGraph;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.MoveSubgraph
 */
export const moveSubgraph = PlatformService.method.moveSubgraph;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.MoveMonograph
 */
export const moveMonograph = PlatformService.method.moveMonograph;

/**
 * CreateMonograph creates a monograph on the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateMonograph
 */
export const createMonograph = PlatformService.method.createMonograph;

/**
 * PublishMonograph pushes the schema of the monograph to the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.PublishMonograph
 */
export const publishMonograph = PlatformService.method.publishMonograph;

/**
 * DeleteMonograph deletes a monograph from the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteMonograph
 */
export const deleteMonograph = PlatformService.method.deleteMonograph;

/**
 * UpdateMonograph updates a monograph with new urls, subscription config and readme
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateMonograph
 */
export const updateMonograph = PlatformService.method.updateMonograph;

/**
 * MigrateMonograph converts a monograph into a federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.MigrateMonograph
 */
export const migrateMonograph = PlatformService.method.migrateMonograph;

/**
 * CreateFederatedSubgraph creates a federated subgraph on the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateFederatedSubgraph
 */
export const createFederatedSubgraph = PlatformService.method.createFederatedSubgraph;

/**
 * PublishFederatedSubgraph pushes the schema of the subgraph to the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.PublishFederatedSubgraph
 */
export const publishFederatedSubgraph = PlatformService.method.publishFederatedSubgraph;

/**
 * CreateFederatedGraph creates a federated graph on the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateFederatedGraph
 */
export const createFederatedGraph = PlatformService.method.createFederatedGraph;

/**
 * DeleteFederatedGraph deletes a federated graph from the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteFederatedGraph
 */
export const deleteFederatedGraph = PlatformService.method.deleteFederatedGraph;

/**
 * DeleteFederatedSubgraph deletes a federated subgraph from the control plane.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteFederatedSubgraph
 */
export const deleteFederatedSubgraph = PlatformService.method.deleteFederatedSubgraph;

/**
 * CheckSubgraphSchema checks if the schema is valid and if it can be composed without conflicts with the provided new subgraph schema.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CheckSubgraphSchema
 */
export const checkSubgraphSchema = PlatformService.method.checkSubgraphSchema;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetProposedSchemaOfCheckedSubgraph
 */
export const getProposedSchemaOfCheckedSubgraph = PlatformService.method.getProposedSchemaOfCheckedSubgraph;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.FixSubgraphSchema
 */
export const fixSubgraphSchema = PlatformService.method.fixSubgraphSchema;

/**
 * UpdateFederatedGraph updates a federated graph with new labels and routing url
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateFederatedGraph
 */
export const updateFederatedGraph = PlatformService.method.updateFederatedGraph;

/**
 * UpdateSubgraph updates a subgraph with new labels and routing url
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateSubgraph
 */
export const updateSubgraph = PlatformService.method.updateSubgraph;

/**
 * CheckFederatedGraph checks if the federated graph can be composed with the new labels provided.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CheckFederatedGraph
 */
export const checkFederatedGraph = PlatformService.method.checkFederatedGraph;

/**
 * WhoAmI returns the identity of the user currently logged in.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.WhoAmI
 */
export const whoAmI = PlatformService.method.whoAmI;

/**
 * GenerateRouterToken generates a temporary router token to fetch the router config.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GenerateRouterToken
 */
export const generateRouterToken = PlatformService.method.generateRouterToken;

/**
 * GetRouterTokens returns the router tokens of a federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetRouterTokens
 */
export const getRouterTokens = PlatformService.method.getRouterTokens;

/**
 * DeleteRouterToken deletes the router token of a federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteRouterToken
 */
export const deleteRouterToken = PlatformService.method.deleteRouterToken;

/**
 * Add persisted operations
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.PublishPersistedOperations
 */
export const publishPersistedOperations = PlatformService.method.publishPersistedOperations;

/**
 * Check if persisted operation has any traffic
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CheckPersistedOperationTraffic
 */
export const checkPersistedOperationTraffic = PlatformService.method.checkPersistedOperationTraffic;

/**
 * Delete/remove a persisted operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeletePersistedOperation
 */
export const deletePersistedOperation = PlatformService.method.deletePersistedOperation;

/**
 * GetPersistedOperations returns operations for the registered client id
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetPersistedOperations
 */
export const getPersistedOperations = PlatformService.method.getPersistedOperations;

/**
 * GetAuditLogs returns the audit logs of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetAuditLogs
 */
export const getAuditLogs = PlatformService.method.getAuditLogs;

/**
 * InitializeCosmoUser takes a bearer token and ensures that the user associated with it (if valid) exists in Cosmo
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.InitializeCosmoUser
 */
export const initializeCosmoUser = PlatformService.method.initializeCosmoUser;

/**
 * ListOrganizations returns all the organization the authenticated user is a member of
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ListOrganizations
 */
export const listOrganizations = PlatformService.method.listOrganizations;

/**
 * GetFederatedGraphs returns the list of federated graphs.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphs
 */
export const getFederatedGraphs = PlatformService.method.getFederatedGraphs;

/**
 * GetFederatedGraphsBySubgraphLabels returns the list of federated graphs based on the subgraph labels
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphsBySubgraphLabels
 */
export const getFederatedGraphsBySubgraphLabels = PlatformService.method.getFederatedGraphsBySubgraphLabels;

/**
 * GetFederatedGraphByName returns the federated graph by name.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphByName
 */
export const getFederatedGraphByName = PlatformService.method.getFederatedGraphByName;

/**
 * GetFederatedGraphSDLByName returns the latest valid SDL of the federated graph by name.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphSDLByName
 */
export const getFederatedGraphSDLByName = PlatformService.method.getFederatedGraphSDLByName;

/**
 * GetSubgraphs returns the list of subgraphs.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphs
 */
export const getSubgraphs = PlatformService.method.getSubgraphs;

/**
 * GetSubgraphByName returns the subgraph by name.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphByName
 */
export const getSubgraphByName = PlatformService.method.getSubgraphByName;

/**
 * GetSubgraphSDLFromLatestComposition returns the latest valid SDL of the subgraph composed with the federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphSDLFromLatestComposition
 */
export const getSubgraphSDLFromLatestComposition = PlatformService.method.getSubgraphSDLFromLatestComposition;

/**
 * GetLatestSubgraphSDL returns the latest SDL of the subgraph by name.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetLatestSubgraphSDL
 */
export const getLatestSubgraphSDL = PlatformService.method.getLatestSubgraphSDL;

/**
 * GetChecksByFederatedGraphName return schema and composition checks that concern a federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetChecksByFederatedGraphName
 */
export const getChecksByFederatedGraphName = PlatformService.method.getChecksByFederatedGraphName;

/**
 * GetCheckSummary returns top level information about a schema check
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCheckSummary
 */
export const getCheckSummary = PlatformService.method.getCheckSummary;

/**
 * GetCheckOperations returns affected operations for a check
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCheckOperations
 */
export const getCheckOperations = PlatformService.method.getCheckOperations;

/**
 * ForceCheckSuccess forces a failed check to be marked as successful
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ForceCheckSuccess
 */
export const forceCheckSuccess = PlatformService.method.forceCheckSuccess;

/**
 * CreateOperationOverrides marks if the given set of changes as safe for an operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOperationOverrides
 */
export const createOperationOverrides = PlatformService.method.createOperationOverrides;

/**
 * RemoveOperationOverride removes a change from the safe-list for an operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RemoveOperationOverrides
 */
export const removeOperationOverrides = PlatformService.method.removeOperationOverrides;

/**
 * CreateOperationIgnoreAllOverride adds an ignore all override for the operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOperationIgnoreAllOverride
 */
export const createOperationIgnoreAllOverride = PlatformService.method.createOperationIgnoreAllOverride;

/**
 * RemoveOperationIgnoreAllOverride removes the ignore all override for the operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RemoveOperationIgnoreAllOverride
 */
export const removeOperationIgnoreAllOverride = PlatformService.method.removeOperationIgnoreAllOverride;

/**
 * GetOperationOverrides retrieves all overrides for an operation hash
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOperationOverrides
 */
export const getOperationOverrides = PlatformService.method.getOperationOverrides;

/**
 * GetAllOverrides returns all overrides for operations within a namespace
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetAllOverrides
 */
export const getAllOverrides = PlatformService.method.getAllOverrides;

/**
 * ToggleChangeOverridesForAllOperations marks all impacting changes of a given check either safe or unsafe
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ToggleChangeOverridesForAllOperations
 */
export const toggleChangeOverridesForAllOperations = PlatformService.method.toggleChangeOverridesForAllOperations;

/**
 * CreateIgnoreOverridesForAllOperations creates ignore override for all operations of a given check
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateIgnoreOverridesForAllOperations
 */
export const createIgnoreOverridesForAllOperations = PlatformService.method.createIgnoreOverridesForAllOperations;

/**
 * GetOperationContent returns the operation body by searching using the hash
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOperationContent
 */
export const getOperationContent = PlatformService.method.getOperationContent;

/**
 * GetFederatedGraphChangelog returns the changelog of the federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphChangelog
 */
export const getFederatedGraphChangelog = PlatformService.method.getFederatedGraphChangelog;

/**
 * CreateFederatedGraphToken creates a federated graph token that is consumed by the router to authenticate requests.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateFederatedGraphToken
 */
export const createFederatedGraphToken = PlatformService.method.createFederatedGraphToken;

/**
 * GetOrganizationBySlug returns a specific organization by its slug
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationBySlug
 */
export const getOrganizationBySlug = PlatformService.method.getOrganizationBySlug;

/**
 * GetOrganizationMembers returns the list of organization members
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationMembers
 */
export const getOrganizationMembers = PlatformService.method.getOrganizationMembers;

/**
 * GetOrganizationMembers returns the list of pending organization invites
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetPendingOrganizationMembers
 */
export const getPendingOrganizationMembers = PlatformService.method.getPendingOrganizationMembers;

/**
 * IsMemberLimitReached returns whether the organization has reached the member limit
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.IsMemberLimitReached
 */
export const isMemberLimitReached = PlatformService.method.isMemberLimitReached;

/**
 * InviteUser invites an user to join the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.InviteUser
 */
export const inviteUser = PlatformService.method.inviteUser;

/**
 * GetAPIKeys returns a list of API keys of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetAPIKeys
 */
export const getAPIKeys = PlatformService.method.getAPIKeys;

/**
 * CreateAPIKey creates an API key for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateAPIKey
 */
export const createAPIKey = PlatformService.method.createAPIKey;

/**
 * UpdateAPIKey updates an API key for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateAPIKey
 */
export const updateAPIKey = PlatformService.method.updateAPIKey;

/**
 * DeleteAPIKey deletes an API key for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteAPIKey
 */
export const deleteAPIKey = PlatformService.method.deleteAPIKey;

/**
 * RemoveOrganizationMember removes the user from the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RemoveOrganizationMember
 */
export const removeOrganizationMember = PlatformService.method.removeOrganizationMember;

/**
 * RemoveInvitation removes the org invitation of the user
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RemoveInvitation
 */
export const removeInvitation = PlatformService.method.removeInvitation;

/**
 * MigrateFromApollo migrates the graphs from apollo to cosmo
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.MigrateFromApollo
 */
export const migrateFromApollo = PlatformService.method.migrateFromApollo;

/**
 * Organization Member Group management
 * CreateOrganizationGroup creates a new organization group
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOrganizationGroup
 */
export const createOrganizationGroup = PlatformService.method.createOrganizationGroup;

/**
 * GetOrganizationGroups returns the list of organization groups
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationGroups
 */
export const getOrganizationGroups = PlatformService.method.getOrganizationGroups;

/**
 * GetOrganizationGroupMembers returns the list of members belonging to the provided organization group
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationGroupMembers
 */
export const getOrganizationGroupMembers = PlatformService.method.getOrganizationGroupMembers;

/**
 * UpdateOrganizationGroup updates the rule list for an organization group
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateOrganizationGroup
 */
export const updateOrganizationGroup = PlatformService.method.updateOrganizationGroup;

/**
 * DeleteOrganizationGroup deletes an existing organization group
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteOrganizationGroup
 */
export const deleteOrganizationGroup = PlatformService.method.deleteOrganizationGroup;

/**
 * CreateOrganizationWebhookConfig create a new webhook config for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOrganizationWebhookConfig
 */
export const createOrganizationWebhookConfig = PlatformService.method.createOrganizationWebhookConfig;

/**
 * GetOrganizationWebhookConfigs returns all webhooks for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationWebhookConfigs
 */
export const getOrganizationWebhookConfigs = PlatformService.method.getOrganizationWebhookConfigs;

/**
 * GetOrganizationWebhookMeta returns the meta data for a particular webhook
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationWebhookMeta
 */
export const getOrganizationWebhookMeta = PlatformService.method.getOrganizationWebhookMeta;

/**
 * UpdateOrganizationWebhookConfig updates an existing webhook for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateOrganizationWebhookConfig
 */
export const updateOrganizationWebhookConfig = PlatformService.method.updateOrganizationWebhookConfig;

/**
 * DeleteOrganizationWebhookConfig deletes an organization webhook
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteOrganizationWebhookConfig
 */
export const deleteOrganizationWebhookConfig = PlatformService.method.deleteOrganizationWebhookConfig;

/**
 * GetOrganizationWebhookHistory retrieves all webhook deliveries for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationWebhookHistory
 */
export const getOrganizationWebhookHistory = PlatformService.method.getOrganizationWebhookHistory;

/**
 * GetWebhookDeliveryDetails retrieves details for a particular webhook
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetWebhookDeliveryDetails
 */
export const getWebhookDeliveryDetails = PlatformService.method.getWebhookDeliveryDetails;

/**
 * RedeliverWebhook triggers the delivery of the given webhook once again
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RedeliverWebhook
 */
export const redeliverWebhook = PlatformService.method.redeliverWebhook;

/**
 * CreateIntegration create a new integration for the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateIntegration
 */
export const createIntegration = PlatformService.method.createIntegration;

/**
 * GetOrganizationIntegrations returns all integrations of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationIntegrations
 */
export const getOrganizationIntegrations = PlatformService.method.getOrganizationIntegrations;

/**
 * UpdateIntegrationConfig updates an existing integration of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateIntegrationConfig
 */
export const updateIntegrationConfig = PlatformService.method.updateIntegrationConfig;

/**
 * DeleteIntegration deletes an organization web integration hook
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteIntegration
 */
export const deleteIntegration = PlatformService.method.deleteIntegration;

/**
 * DeleteUser deletes the user
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteUser
 */
export const deleteUser = PlatformService.method.deleteUser;

/**
 * DeleteOrganization deletes an organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteOrganization
 */
export const deleteOrganization = PlatformService.method.deleteOrganization;

/**
 * RestoreOrganization restore an organization pending deletion
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RestoreOrganization
 */
export const restoreOrganization = PlatformService.method.restoreOrganization;

/**
 * LeaveOrganization removes a member from the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.LeaveOrganization
 */
export const leaveOrganization = PlatformService.method.leaveOrganization;

/**
 * UpdateOrganizationDetails updates the name and slug of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateOrganizationDetails
 */
export const updateOrganizationDetails = PlatformService.method.updateOrganizationDetails;

/**
 * UpdateOrgMemberGroup updates the group of an organization member
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateOrgMemberGroup
 */
export const updateOrgMemberGroup = PlatformService.method.updateOrgMemberGroup;

/**
 * IsGitHubAppInstalled checks if the cosmo github app is installed to a repository
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.IsGitHubAppInstalled
 */
export const isGitHubAppInstalled = PlatformService.method.isGitHubAppInstalled;

/**
 * CreateOIDCProvider adds an oidc provider to the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOIDCProvider
 */
export const createOIDCProvider = PlatformService.method.createOIDCProvider;

/**
 * GetOIDCProvider gets the oidc provider connected the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOIDCProvider
 */
export const getOIDCProvider = PlatformService.method.getOIDCProvider;

/**
 * DeleteOIDCProvider deletes the oidc provider connected the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteOIDCProvider
 */
export const deleteOIDCProvider = PlatformService.method.deleteOIDCProvider;

/**
 * UpdateIDPMappers updates the mappings of the oidc provider
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateIDPMappers
 */
export const updateIDPMappers = PlatformService.method.updateIDPMappers;

/**
 * GetClients returns all the clients of the federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetClients
 */
export const getClients = PlatformService.method.getClients;

/**
 * GetRouters returns all active routers of the federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetRouters
 */
export const getRouters = PlatformService.method.getRouters;

/**
 * GetInvitations returns all the invitations a user has received
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetInvitations
 */
export const getInvitations = PlatformService.method.getInvitations;

/**
 * AcceptOrDeclineInvitation accepts or declines the invitation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.AcceptOrDeclineInvitation
 */
export const acceptOrDeclineInvitation = PlatformService.method.acceptOrDeclineInvitation;

/**
 * GetCompositions returns all the compositions of the federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCompositions
 */
export const getCompositions = PlatformService.method.getCompositions;

/**
 * GetCompositionDetails returns the details of that composition
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCompositionDetails
 */
export const getCompositionDetails = PlatformService.method.getCompositionDetails;

/**
 * GetSdlBySchemaVersion returns the sdl based on the schema version
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSdlBySchemaVersion
 */
export const getSdlBySchemaVersion = PlatformService.method.getSdlBySchemaVersion;

/**
 * GetChangelogBySchemaVersion returns the changelog based on the schema version
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetChangelogBySchemaVersion
 */
export const getChangelogBySchemaVersion = PlatformService.method.getChangelogBySchemaVersion;

/**
 * GetUserAccessibleResources returns all the federated and subgraphs where the user has write permissions
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetUserAccessibleResources
 */
export const getUserAccessibleResources = PlatformService.method.getUserAccessibleResources;

/**
 * UpdateFeatureSettings updates the setinngs of features(ai, rbac, scim) of the organization
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateFeatureSettings
 */
export const updateFeatureSettings = PlatformService.method.updateFeatureSettings;

/**
 * GetSubgraphMembers gets all the members of the subgraph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphMembers
 */
export const getSubgraphMembers = PlatformService.method.getSubgraphMembers;

/**
 * AddReadme adds a readme of a target, can be a subgraph or a federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.AddReadme
 */
export const addReadme = PlatformService.method.addReadme;

/**
 * GetUserAccessiblePermissions returns all the federated and subgraphs where the user has write permissions
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetUserAccessiblePermissions
 */
export const getUserAccessiblePermissions = PlatformService.method.getUserAccessiblePermissions;

/**
 * CreateFeatureFlag creates a new feature flag for the selected feature graphs
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateFeatureFlag
 */
export const createFeatureFlag = PlatformService.method.createFeatureFlag;

/**
 * DeleteFeatureFlag deletes an existing feature flag
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteFeatureFlag
 */
export const deleteFeatureFlag = PlatformService.method.deleteFeatureFlag;

/**
 * UpdateFeatureFlag updates a new feature flag for the selected feature graphs
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateFeatureFlag
 */
export const updateFeatureFlag = PlatformService.method.updateFeatureFlag;

/**
 * EnableFeatureFlag enables/disables a feature flag
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.EnableFeatureFlag
 */
export const enableFeatureFlag = PlatformService.method.enableFeatureFlag;

/**
 * Analytics
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetAnalyticsView
 */
export const getAnalyticsView = PlatformService.method.getAnalyticsView;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetDashboardAnalyticsView
 */
export const getDashboardAnalyticsView = PlatformService.method.getDashboardAnalyticsView;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetTrace
 */
export const getTrace = PlatformService.method.getTrace;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetGraphMetrics
 */
export const getGraphMetrics = PlatformService.method.getGraphMetrics;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetMetricsErrorRate
 */
export const getMetricsErrorRate = PlatformService.method.getMetricsErrorRate;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphMetrics
 */
export const getSubgraphMetrics = PlatformService.method.getSubgraphMetrics;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphMetricsErrorRate
 */
export const getSubgraphMetricsErrorRate = PlatformService.method.getSubgraphMetricsErrorRate;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFieldUsage
 */
export const getFieldUsage = PlatformService.method.getFieldUsage;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOrganizationRequestsCount
 */
export const getOrganizationRequestsCount = PlatformService.method.getOrganizationRequestsCount;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateOrganization
 */
export const createOrganization = PlatformService.method.createOrganization;

/**
 * EnableLintingForTheNamespace enables the lint check for the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.EnableLintingForTheNamespace
 */
export const enableLintingForTheNamespace = PlatformService.method.enableLintingForTheNamespace;

/**
 * ConfigureNamespaceLintConfig configures the lint config of the organization.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ConfigureNamespaceLintConfig
 */
export const configureNamespaceLintConfig = PlatformService.method.configureNamespaceLintConfig;

/**
 * GetNamespaceLintConfig returns the lint config of the namespace.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespaceLintConfig
 */
export const getNamespaceLintConfig = PlatformService.method.getNamespaceLintConfig;

/**
 * GetNamespaceChecksConfig returns the checks config of the namespace.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespaceChecksConfig
 */
export const getNamespaceChecksConfig = PlatformService.method.getNamespaceChecksConfig;

/**
 * UpdateNamespaceChecksConfig updates the checks configuration for the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateNamespaceChecksConfig
 */
export const updateNamespaceChecksConfig = PlatformService.method.updateNamespaceChecksConfig;

/**
 * EnablePruningForTheNamespace enables the graph pruning check for the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.EnableGraphPruning
 */
export const enableGraphPruning = PlatformService.method.enableGraphPruning;

/**
 * ConfigureNamespaceGraphPruningConfig configures the graph pruning config of the organization.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ConfigureNamespaceGraphPruningConfig
 */
export const configureNamespaceGraphPruningConfig = PlatformService.method.configureNamespaceGraphPruningConfig;

/**
 * GetNamespaceGraphPruningConfig returns the graph pruning config of the namespace.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespaceGraphPruningConfig
 */
export const getNamespaceGraphPruningConfig = PlatformService.method.getNamespaceGraphPruningConfig;

/**
 * GetFeatureFlags returns the feature flags of the namespace
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFeatureFlags
 */
export const getFeatureFlags = PlatformService.method.getFeatureFlags;

/**
 * GetFeatureFlagByName returns the feature flag of the namespace
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFeatureFlagByName
 */
export const getFeatureFlagByName = PlatformService.method.getFeatureFlagByName;

/**
 * GetFeatureSubgraphsByFeatureFlag returns the feature subgraphs of a feature flag
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFeatureSubgraphsByFeatureFlag
 */
export const getFeatureSubgraphsByFeatureFlag = PlatformService.method.getFeatureSubgraphsByFeatureFlag;

/**
 * GetFeatureSubgraphs returns the list of feature subgraphs.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFeatureSubgraphs
 */
export const getFeatureSubgraphs = PlatformService.method.getFeatureSubgraphs;

/**
 * GetFeatureFlagsByFederatedGraph returns the list of feature flags which match the label matchers of the federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFeatureFlagsByFederatedGraph
 */
export const getFeatureFlagsByFederatedGraph = PlatformService.method.getFeatureFlagsByFederatedGraph;

/**
 * GetFederatedGraphById returns the federated graph by id.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetFederatedGraphById
 */
export const getFederatedGraphById = PlatformService.method.getFederatedGraphById;

/**
 * GetSubgraphById returns the subgraph by id.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphById
 */
export const getSubgraphById = PlatformService.method.getSubgraphById;

/**
 * PushCacheWarmerOperation adds a operation to the list of cache warmer operations.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.PushCacheWarmerOperation
 */
export const pushCacheWarmerOperation = PlatformService.method.pushCacheWarmerOperation;

/**
 * GetCacheWarmerOperations returns the list of cache warmer operations.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCacheWarmerOperations
 */
export const getCacheWarmerOperations = PlatformService.method.getCacheWarmerOperations;

/**
 * ComputeCacheWarmerOperations computes the list of cache warmer operations.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ComputeCacheWarmerOperations
 */
export const computeCacheWarmerOperations = PlatformService.method.computeCacheWarmerOperations;

/**
 * ConfigureCacheWarmer enables cache warmer for the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ConfigureCacheWarmer
 */
export const configureCacheWarmer = PlatformService.method.configureCacheWarmer;

/**
 * GetCacheWarmerConfig gets the config of cache warming for that namespace.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetCacheWarmerConfig
 */
export const getCacheWarmerConfig = PlatformService.method.getCacheWarmerConfig;

/**
 * DeleteCacheWarmerOperation deletes a cache warmer operation.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.DeleteCacheWarmerOperation
 */
export const deleteCacheWarmerOperation = PlatformService.method.deleteCacheWarmerOperation;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetSubgraphCheckExtensionsConfig
 */
export const getSubgraphCheckExtensionsConfig = PlatformService.method.getSubgraphCheckExtensionsConfig;

/**
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ConfigureSubgraphCheckExtensions
 */
export const configureSubgraphCheckExtensions = PlatformService.method.configureSubgraphCheckExtensions;

/**
 *
 * Billing
 * -----------------------------------------------------------------------------------------------------------------------------
 * Return the available billing plans
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetBillingPlans
 */
export const getBillingPlans = PlatformService.method.getBillingPlans;

/**
 * Create a Stripe checkout session
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateCheckoutSession
 */
export const createCheckoutSession = PlatformService.method.createCheckoutSession;

/**
 * Create a Stripe billing portal session
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateBillingPortalSession
 */
export const createBillingPortalSession = PlatformService.method.createBillingPortalSession;

/**
 * Upgrade the current plan
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpgradePlan
 */
export const upgradePlan = PlatformService.method.upgradePlan;

/**
 * Router Compatibility Versions
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ListRouterCompatibilityVersions
 */
export const listRouterCompatibilityVersions = PlatformService.method.listRouterCompatibilityVersions;

/**
 * Graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.SetGraphRouterCompatibilityVersion
 */
export const setGraphRouterCompatibilityVersion = PlatformService.method.setGraphRouterCompatibilityVersion;

/**
 * Proposal
 * Create a proposal for a federated graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.CreateProposal
 */
export const createProposal = PlatformService.method.createProposal;

/**
 * Get a proposal by id
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetProposal
 */
export const getProposal = PlatformService.method.getProposal;

/**
 * Update a proposal
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UpdateProposal
 */
export const updateProposal = PlatformService.method.updateProposal;

/**
 * EnableProposalsForNamespace enables the proposals for the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.EnableProposalsForNamespace
 */
export const enableProposalsForNamespace = PlatformService.method.enableProposalsForNamespace;

/**
 * ConfigureNamespaceProposalConfig configures the proposal config of the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ConfigureNamespaceProposalConfig
 */
export const configureNamespaceProposalConfig = PlatformService.method.configureNamespaceProposalConfig;

/**
 * GetNamespaceProposalConfig returns the proposal config of the namespace passed.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetNamespaceProposalConfig
 */
export const getNamespaceProposalConfig = PlatformService.method.getNamespaceProposalConfig;

/**
 * GetProposalsByFederatedGraph returns proposals for a federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetProposalsByFederatedGraph
 */
export const getProposalsByFederatedGraph = PlatformService.method.getProposalsByFederatedGraph;

/**
 * GetProposalChecks returns checks for a proposal.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetProposalChecks
 */
export const getProposalChecks = PlatformService.method.getProposalChecks;

/**
 * GetOperations returns the operations of a federated graph.
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOperations
 */
export const getOperations = PlatformService.method.getOperations;

/**
 * GetClientsFromAnalytics returns all the clients of the federated graph from the analytics
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetClientsFromAnalytics
 */
export const getClientsFromAnalytics = PlatformService.method.getClientsFromAnalytics;

/**
 * GetOperationClients returns the clients that have used a specific operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOperationClients
 */
export const getOperationClients = PlatformService.method.getOperationClients;

/**
 * GetOperationDeprecatedFields returns the deprecated fields used in a specific operation
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.GetOperationDeprecatedFields
 */
export const getOperationDeprecatedFields = PlatformService.method.getOperationDeprecatedFields;

/**
 * ValidateAndFetchPluginData validates the limit of plugins and returns the latest version and token
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.ValidateAndFetchPluginData
 */
export const validateAndFetchPluginData = PlatformService.method.validateAndFetchPluginData;

/**
 * LinkSubgraph links one subgraph to another
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.LinkSubgraph
 */
export const linkSubgraph = PlatformService.method.linkSubgraph;

/**
 * UnlinkSubgraph unlinks one subgraph from another
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.UnlinkSubgraph
 */
export const unlinkSubgraph = PlatformService.method.unlinkSubgraph;

/**
 * VerifyAPIKeyGraphAccess checks if the token or the jwt has organization admin or developer  and checks if the token has permissions to write to the graph
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.VerifyAPIKeyGraphAccess
 */
export const verifyAPIKeyGraphAccess = PlatformService.method.verifyAPIKeyGraphAccess;

/**
 * RecomposeGraph triggers a recomposition of the federated graph (or monograph) using its current subgraphs
 *
 * @generated from rpc wg.cosmo.platform.v1.PlatformService.RecomposeGraph
 */
export const recomposeGraph = PlatformService.method.recomposeGraph;
