name: 'Codecov Download and Upload'
description: 'Download coverage artifacts from previous PR runs and upload to Codecov'

inputs:
  coverage-path:
    description: 'Path to coverage files'
    required: true
  workflow-paths:
    description: 'Comma-separated list of workflow paths for artifact lookup (e.g., ".github/workflows/router-ci.yaml,.github/workflows/cli-ci.yaml")'
    required: true
  override-commit:
    description: 'Commit SHA to override in Codecov'
    required: true
  merge-commit-sha:
    description: 'Merge commit SHA to look up the PR and find head SHA'
    required: false
    default: ''
  codecov-token:
    description: 'Codecov token for uploading'
    required: true
  github-token:
    description: 'GitHub token for artifact operations'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Find latest successful PR runs for this commit
      id: find-artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        MERGE_COMMIT_SHA: ${{ inputs.merge-commit-sha }}
        CURRENT_RUN_ID: ${{ github.run_id }}
        ARTIFACT_NAME_PATTERN: codecov
        WORKFLOW_PATHS: ${{ inputs.workflow-paths }}
      run: ./.github/scripts/find-codecov-artifact.sh

    - name: Download coverage artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        ARTIFACTS_JSON: ${{ steps.find-artifacts.outputs.artifacts_json }}
        COVERAGE_PATH: ${{ inputs.coverage-path }}
      run: |
        echo "Downloading artifacts..."
        echo "$ARTIFACTS_JSON" | jq -c '.[]' | while read -r artifact; do
          run_id=$(echo "$artifact" | jq -r '.run_id')
          artifact_id=$(echo "$artifact" | jq -r '.artifact_id')
          artifact_name=$(echo "$artifact" | jq -r '.artifact_name')
        
          echo "Downloading artifact: $artifact_name (ID: $artifact_id) from run: $run_id"
        
          # Download artifact using GitHub CLI
          gh run download "$run_id" \
            --repo "$REPO" \
            --name "$artifact_name" \
            --dir "$COVERAGE_PATH/$artifact_name"
        
          if [ $? -eq 0 ]; then
            echo "✓ Successfully downloaded $artifact_name"
          else
            echo "✗ Failed to download $artifact_name" >&2
            exit 1
          fi
        done
        
        echo "All artifacts downloaded successfully"

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        override_commit: ${{ inputs.override-commit }}
        override_branch: main
        directory: ${{ inputs.coverage-path }}
