package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/deferdemo"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/reviews/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/reviews/subgraph/model"
)

// Reviews is the resolver for the reviews field.
func (r *productResolver) Reviews(ctx context.Context, obj *model.Product) ([]*model.Review, error) {
	if err := r.Latencies.Wait(ctx, deferdemo.FieldReviewsProductReviews); err != nil {
		return nil, err
	}
	return reviewsByProductID(obj.ID), nil
}

// RatingSummary is the resolver for the ratingSummary field.
func (r *productResolver) RatingSummary(ctx context.Context, obj *model.Product) (*model.RatingSummary, error) {
	if err := r.Latencies.Wait(ctx, deferdemo.FieldReviewsProductRatingSummary); err != nil {
		return nil, err
	}
	return &model.RatingSummary{Average: 4.5, Count: 2}, nil
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
