name: "Build and Push Image (PR only)"
description: "This action to build and push docker image for CI in Pull Request only."
inputs:
  image_description:
    description: "The description of the container"
  image_name:
    description: "The name of the container"
    required: true
  dockerfile:
    description: "The Dockerfile to use"
    default: "Dockerfile"
  docker_context:
    description: "The Docker context to use"
    default: "."
  image_platforms:
    description: "The platforms to build the image for"
    default: "linux/amd64,linux/arm64"
  push:
    description: "Whether to push the image to the GitHub container registry"
    default: "true"
  image_version:
    description: "The version of the image"
    required: true
  image_respository:
    description: "The repository of the image"
    required: true
  build_args:
    description: "The build arguments to pass to the build"
    default: ""
outputs:
  image_ref:
    description: "The reference of the image that was built"
    value: "${{ github.image_respository }}/${{ github.repository }}/${{ inputs.image_name }}:sha-${{ github.sha }}"

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Container registry (With write access)
      uses: docker/login-action@v3
      if: ${{ inputs.docker_username != '' && inputs.docker_password != '' }}
      with:
        registry: docker.io
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image_respository }}/${{ github.repository }}/${{ inputs.image_name }}
        tags: |
          type=ref,event=pr
          # minimal (short sha)
          type=sha
          # full length commit sha
          type=raw,value=sha-${{ github.sha }}
          type=raw,value=${{ inputs.image_version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set BUILD_TIME env
      shell: bash
      run: echo BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> ${GITHUB_ENV}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        # This is a limitation of GitHub. Only organization members can push to GitHub Container Registry
        # For now, we will disable the push to the GitHub Container Registry for external contributors
        push: ${{ inputs.push == 'true' }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.docker_context }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.image_platforms }}
        outputs:
          type=image,name=target,annotation-index.org.opencontainers.image.description=${{ inputs.image_description }}
          type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/wundergraph/cosmo
          type=image,name=target,annotation-index.org.opencontainers.image.licenses=Apache-2.0
        build-args: |
          VERSION=${{ github.sha }}
          DATE=${{ env.BUILD_TIME }}
          COMMIT=${{ github.sha }}
          ${{ inputs.build_args }}