FROM golang:1.20 as builder

WORKDIR /app

COPY products/go.mod products/go.sum ./

RUN mkdir ../otel
COPY otel ../otel/

RUN go mod download && go mod verify

COPY products .

RUN go build -o server

ENTRYPOINT [ "./server" ]

EXPOSE 4004
