FROM golang:1.20 as builder

WORKDIR /app

COPY employees/go.mod employees/go.sum ./

RUN mkdir ../otel
COPY otel ../otel/

RUN go mod download && go mod verify

COPY employees .

RUN go build -o server

ENTRYPOINT [ "./server" ]

EXPOSE 4001
