FROM golang:1.20 as builder

WORKDIR /app

COPY hobbies/go.mod hobbies/go.sum ./

RUN mkdir ../otel
COPY otel ../otel/

RUN go mod download && go mod verify

COPY hobbies .

RUN go build -o server

ENTRYPOINT [ "./server" ]

EXPOSE 4003
