FROM golang:1.20 as builder

WORKDIR /app

COPY family/go.mod family/go.sum ./

RUN mkdir ../otel
COPY otel ../otel/

RUN go mod download && go mod verify

COPY family .

RUN go build -o server

ENTRYPOINT [ "./server" ]

EXPOSE 4002
