DO $$ BEGIN
 CREATE TYPE "schema_change_type" AS ENUM('FIELD_ARGUMENT_DESCRIPTION_CHANGED', 'FIELD_ARGUMENT_DEFAULT_CHANGED', 'FIELD_ARGUMENT_TYPE_CHANGED', 'DIRECTIVE_REMOVED', 'DIRECTIVE_ADDED', 'DIRECTIVE_DESCRIPTION_CHANGED', 'DIRECTIVE_LOCATION_ADDED', 'DIRECTIVE_LOCATION_REMOVED', 'DIRECTIVE_ARGUMENT_ADDED', 'DIRECTIVE_ARGUMENT_REMOVED', 'DIRECTIVE_ARGUMENT_DESCRIPTION_CHANGED', 'DIRECTIVE_ARGUMENT_DEFAULT_VALUE_CHANGED', 'DIRECTIVE_ARGUMENT_TYPE_CHANGED', 'ENUM_VALUE_REMOVED', 'ENUM_VALUE_ADDED', 'ENUM_VALUE_DESCRIPTION_CHANGED', 'ENUM_VALUE_DEPRECATION_REASON_CHANGED', 'ENUM_VALUE_DEPRECATION_REASON_ADDED', 'ENUM_VALUE_DEPRECATION_REASON_REMOVED', 'FIELD_REMOVED', 'FIELD_ADDED', 'FIELD_DESCRIPTION_CHANGED', 'FIELD_DESCRIPTION_ADDED', 'FIELD_DESCRIPTION_REMOVED', 'FIELD_DEPRECATION_ADDED', 'FIELD_DEPRECATION_REMOVED', 'FIELD_DEPRECATION_REASON_CHANGED', 'FIELD_DEPRECATION_REASON_ADDED', 'FIELD_DEPRECATION_REASON_REMOVED', 'FIELD_TYPE_CHANGED', 'FIELD_ARGUMENT_ADDED', 'FIELD_ARGUMENT_REMOVED', 'INPUT_FIELD_REMOVED', 'INPUT_FIELD_ADDED', 'INPUT_FIELD_DESCRIPTION_ADDED', 'INPUT_FIELD_DESCRIPTION_REMOVED', 'INPUT_FIELD_DESCRIPTION_CHANGED', 'INPUT_FIELD_DEFAULT_VALUE_CHANGED', 'INPUT_FIELD_TYPE_CHANGED', 'OBJECT_TYPE_INTERFACE_ADDED', 'OBJECT_TYPE_INTERFACE_REMOVED', 'SCHEMA_QUERY_TYPE_CHANGED', 'SCHEMA_MUTATION_TYPE_CHANGED', 'SCHEMA_SUBSCRIPTION_TYPE_CHANGED', 'TYPE_REMOVED', 'TYPE_ADDED', 'TYPE_KIND_CHANGED', 'TYPE_DESCRIPTION_CHANGED', 'TYPE_DESCRIPTION_REMOVED', 'TYPE_DESCRIPTION_ADDED', 'UNION_MEMBER_REMOVED', 'UNION_MEMBER_ADDED');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "schema_check_change_action" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"schema_check_id" uuid NOT NULL,
	"change_type" "schema_change_type",
	"change_message" text,
	"path" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "schema_checks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"target_id" uuid NOT NULL,
	"is_composable" boolean DEFAULT false,
	"composition_errors" jsonb,
	"proposed_subgraph_schema_sdl" text,
	"composed_schema_sdl" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "schema_check_change_action" ADD CONSTRAINT "schema_check_change_action_schema_check_id_schema_checks_id_fk" FOREIGN KEY ("schema_check_id") REFERENCES "schema_checks"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "schema_checks" ADD CONSTRAINT "schema_checks_target_id_targets_id_fk" FOREIGN KEY ("target_id") REFERENCES "targets"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
