CREATE INDEX IF NOT EXISTS "akp_api_key_id_idx" ON "api_key_permissions" USING btree ("api_key_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "akr_api_key_id_idx" ON "api_key_resources" USING btree ("api_key_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "akr_target_id_idx" ON "api_key_resources" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ak_user_id_idx" ON "api_keys" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ak_organization_id_idx" ON "api_keys" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "auditlogs_organization_idx" ON "audit_logs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "auditlogs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "billsubs_organization_id_idx" ON "billing_subscriptions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_created_by_id_idx" ON "contracts" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_updated_by_id_idx" ON "contracts" USING btree ("updated_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_downstream_federated_graph_id_idx" ON "contracts" USING btree ("downstream_federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "dist_discussion_id_idx" ON "discussion_thread" USING btree ("discussion_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "dist_created_by_id_idx" ON "discussion_thread" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "dis_target_id_idx" ON "discussions" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "dis_schema_version_id_idx" ON "discussions" USING btree ("schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fffs_feature_flag_id_idx" ON "feature_flags_to_feature_subgraphs" USING btree ("feature_flag_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fffs_feature_subgraph_id_idx" ON "feature_flags_to_feature_subgraphs" USING btree ("feature_subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ff_organization_id_idx" ON "feature_flags" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ff_namespace_id_idx" ON "feature_flags" USING btree ("namespace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ff_created_by_idx" ON "feature_flags" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fsbs_feature_subgraph_id_idx" ON "feature_subgraphs_to_base_subgraphs" USING btree ("feature_subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fsbs_base_subgraph_id_idx" ON "feature_subgraphs_to_base_subgraphs" USING btree ("base_subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgc_created_by_id_idx" ON "federated_graph_clients" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgc_updated_by_id_idx" ON "federated_graph_clients" USING btree ("updated_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgpo_created_by_id_idx" ON "federated_graph_persisted_operations" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgpo_updated_by_id_idx" ON "federated_graph_persisted_operations" USING btree ("updated_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgpo_client_id_idx" ON "federated_graph_persisted_operations" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgs_target_id_idx" ON "federated_graphs" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgs_composed_schema_version_id_idx" ON "federated_graphs" USING btree ("composed_schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgffsv_federated_graph_id_idx" ON "federated_graphs_to_feature_flag_schema_versions" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgffsv_base_composition_schema_version_id_idx" ON "federated_graphs_to_feature_flag_schema_versions" USING btree ("base_composition_schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgffsv_composed_schema_version_id_idx" ON "federated_graphs_to_feature_flag_schema_versions" USING btree ("composed_schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgffsv_feature_flag_id_idx" ON "federated_graphs_to_feature_flag_schema_versions" USING btree ("feature_flag_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgp_subgraph_id_idx" ON "field_grace_period" USING btree ("subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgp_organization_id_idx" ON "field_grace_period" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fgp_namespace_id_idx" ON "field_grace_period" USING btree ("namespace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gat_organization_id_idx" ON "graph_api_tokens" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gat_federated_graph_id_idx" ON "graph_api_tokens" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "gat_created_by_idx" ON "graph_api_tokens" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "graphcompsub_graph_composition_id_idx" ON "graph_composition_subgraphs" USING btree ("graph_composition_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "graphcompsub_schema_version_id_idx" ON "graph_composition_subgraphs" USING btree ("schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "graphcomp_schema_version_id_idx" ON "graph_compositions" USING btree ("schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "graphcomp_created_by_id_idx" ON "graph_compositions" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grk_organization_id_idx" ON "graph_request_keys" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grk_federated_graph_id_idx" ON "graph_request_keys" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "nsgpcc_namespace_id_idx" ON "namespace_graph_pruning_check_config" USING btree ("namespace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "nslcc_namespace_id_idx" ON "namespace_lint_check_config" USING btree ("namespace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ns_organization_id_idx" ON "namespaces" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ns_created_by_idx" ON "namespaces" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oidcp_organization_id_idx" ON "oidc_providers" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oco_created_by_idx" ON "operation_change_overrides" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oiao_created_by_idx" ON "operation_ignore_all_overrides" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orgf_organization_id_idx" ON "organization_features" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orgint_organization_id_idx" ON "organization_integrations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orginv_organization_id_idx" ON "organization_invitations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orginv_user_id_idx" ON "organization_invitations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orginv_invited_by_idx" ON "organization_invitations" USING btree ("invited_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orgwc_organization_id_idx" ON "organization_webhook_configs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orgs_created_by_idx" ON "organizations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orgm_organization_id_idx" ON "organization_members" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scca_schema_check_id_idx" ON "schema_check_change_action" USING btree ("schema_check_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sccou_schema_check_change_action_id_idx" ON "schema_check_change_operation_usage" USING btree ("schema_check_change_action_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sccou_federated_graph_id_idx" ON "schema_check_change_operation_usage" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scc_schema_check_id_idx" ON "schema_check_composition" USING btree ("schema_check_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scc_target_id_idx" ON "schema_check_composition" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scfg_check_id_idx" ON "schema_check_federated_graphs" USING btree ("check_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scfg_federated_graph_id_idx" ON "schema_check_federated_graphs" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scgpa_schema_check_id_idx" ON "schema_check_graph_pruning_action" USING btree ("schema_check_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scgpa_federated_graph_id_idx" ON "schema_check_graph_pruning_action" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sclact_schema_check_id_idx" ON "schema_check_lint_action" USING btree ("schema_check_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sc_target_id_idx" ON "schema_checks" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sv_organization_id_idx" ON "schema_versions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "svca_schema_version_id_idx" ON "schema_version_change_action" USING btree ("schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "slackinst_organization_id_idx" ON "slack_installations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "slackintconf_integration_id_idx" ON "slack_integration_configs" USING btree ("integration_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "slacksuec_slack_integration_config_id_idx" ON "slack_schema_update_event_configs" USING btree ("slack_integration_config_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "slacksuec_federated_graph_id_idx" ON "slack_schema_update_event_configs" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sm_user_id_idx" ON "subgraph_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sm_subgraph_id_idx" ON "subgraph_members" USING btree ("subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subgraphs_target_id_idx" ON "subgraphs" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subgraphs_schema_version_id_idx" ON "subgraphs" USING btree ("schema_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fs_federated_graph_id_idx" ON "federated_subgraphs" USING btree ("federated_graph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fs_subgraph_id_idx" ON "federated_subgraphs" USING btree ("subgraph_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tlm_target_id_idx" ON "target_label_matchers" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_organization_id_idx" ON "targets" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_created_by_idx" ON "targets" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_namespace_id_idx" ON "targets" USING btree ("namespace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhd_organization_id_idx" ON "webhook_deliveries" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhd_created_by_id_idx" ON "webhook_deliveries" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wgsu_webhook_id_idx" ON "webhook_graph_schema_update" USING btree ("webhook_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wgsu_federated_graph_id_idx" ON "webhook_graph_schema_update" USING btree ("federated_graph_id");