---
name: go-linter
description: This action validates the codebase using static analysis tools
inputs:
  working-directory:
    description: The working directory to run the linter in
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Run go vet
      run: go vet ./...
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run staticcheck linter
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: 2025.1.1
        install-go: false
        working-directory: ${{ inputs.working-directory }}
