// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file wg/cosmo/webhooks/common.proto (package wg.cosmo.webhooks, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message wg.cosmo.webhooks.FederatedGraph
 */
export class FederatedGraph extends Message<FederatedGraph> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<FederatedGraph>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wg.cosmo.webhooks.FederatedGraph";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FederatedGraph {
    return new FederatedGraph().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FederatedGraph {
    return new FederatedGraph().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FederatedGraph {
    return new FederatedGraph().fromJsonString(jsonString, options);
  }

  static equals(a: FederatedGraph | PlainMessage<FederatedGraph> | undefined, b: FederatedGraph | PlainMessage<FederatedGraph> | undefined): boolean {
    return proto3.util.equals(FederatedGraph, a, b);
  }
}

