// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file wg/cosmo/node/v1/node.proto (package wg.cosmo.node.v1, syntax proto3)
/* eslint-disable */

import { NodeService } from "./node_pb";

/**
 * @generated from rpc wg.cosmo.node.v1.NodeService.SelfRegister
 */
export const selfRegister = NodeService.method.selfRegister;
