// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file wg/cosmo/node/v1/node.proto (package wg.cosmo.node.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetConfigRequest, GetConfigResponse, SelfRegisterRequest, SelfRegisterResponse } from "./node_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wg.cosmo.node.v1.NodeService
 */
export const NodeService = {
  typeName: "wg.cosmo.node.v1.NodeService",
  methods: {
    /**
     * @generated from rpc wg.cosmo.node.v1.NodeService.GetLatestValidRouterConfig
     * @deprecated
     */
    getLatestValidRouterConfig: {
      name: "GetLatestValidRouterConfig",
      I: GetConfigRequest,
      O: GetConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wg.cosmo.node.v1.NodeService.SelfRegister
     */
    selfRegister: {
      name: "SelfRegister",
      I: SelfRegisterRequest,
      O: SelfRegisterResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

