package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"deferdemo/media/graph/model"
)

// FindArticleByID is the resolver for the findArticleByID field.
func (r *entityResolver) FindArticleByID(ctx context.Context, id string) (*model.Article, error) {
	// media owns Article.heroImageUrl via @override(from: "content").
	return &model.Article{ID: id, HeroImageURL: articleHeroImageURLs[id]}, nil
}

// FindAssetByID is the resolver for the findAssetByID field.
func (r *entityResolver) FindAssetByID(ctx context.Context, id string) (model.Asset, error) {
	return assetByID(id), nil
}

// FindImageAssetByID is the resolver for the findImageAssetByID field.
func (r *entityResolver) FindImageAssetByID(ctx context.Context, id string) (*model.ImageAsset, error) {
	return imageAssets[id], nil
}

// FindMediaAssetByID is the resolver for the findMediaAssetByID field.
func (r *entityResolver) FindMediaAssetByID(ctx context.Context, id string) (*model.MediaAsset, error) {
	return mediaAssets[id], nil
}

// FindVideoAssetByID is the resolver for the findVideoAssetByID field.
func (r *entityResolver) FindVideoAssetByID(ctx context.Context, id string) (*model.VideoAsset, error) {
	return videoAssets[id], nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
