package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"deferdemo/media/graph/model"
	"time"
)

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (model.Asset, error) {
	return assetByID(id), nil
}

// TranscodeProgress is the resolver for the transcodeProgress field.
// Slow defer target (DESIGN §6): mock transcode latency. Value stays fixed.
func (r *videoAssetResolver) TranscodeProgress(ctx context.Context, obj *model.VideoAsset) (float64, error) {
	time.Sleep(150 * time.Millisecond)
	return obj.TranscodeProgress, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// VideoAsset returns VideoAssetResolver implementation.
func (r *Resolver) VideoAsset() VideoAssetResolver { return &videoAssetResolver{r} }

type queryResolver struct{ *Resolver }
type videoAssetResolver struct{ *Resolver }
