---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphqlmetrics.fullname" . }}-configmap
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the configmap changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "graphqlmetrics.labels" . | nindent 4 }}
data:
  listenAddr: "{{ .Values.configuration.listenAddr }}"
  logLevel: "{{ .Values.configuration.logLevel }}"
  prometheusEnabled: "{{ .Values.configuration.prometheus.enabled }}"
  {{- if .Values.configuration.prometheus.enabled }}
  prometheusListenAddr: "{{ .Values.configuration.prometheus.host }}:{{ .Values.configuration.prometheus.port }}"
  prometheusPath: "{{ .Values.configuration.prometheus.path }}"
  {{ end }}
