---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphqlmetrics.fullname" . }}
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the secret changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "graphqlmetrics.labels" . | nindent 4 }}
stringData:
  clickhouseDsn: "{{ .Values.configuration.clickhouseDsn }}"
  jwtSecret: "{{ .Values.global.controlplane.jwtSecret }}"