apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphqlmetrics.fullname" . }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "graphqlmetrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphqlmetrics.selectorLabels" . | nindent 4 }}
