package subgraph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachegraph_ext/subgraph/generated"
	"github.com/wundergraph/cosmo/demo/pkg/subgraphs/cachegraph_ext/subgraph/model"
)

// PersonalizedRecommendation is the resolver for the personalizedRecommendation field.
func (r *articleResolver) PersonalizedRecommendation(ctx context.Context, obj *model.Article) (string, error) {
	if obj.CurrentViewer == nil {
		return "Sign in to get personalized recommendations.", nil
	}
	return fmt.Sprintf("Hey %s, based on your interests you'll love this article!", obj.CurrentViewer.Name), nil
}

// RelatedArticles is the resolver for the relatedArticles field.
func (r *articleResolver) RelatedArticles(ctx context.Context, obj *model.Article) ([]*model.Article, error) {
	ext := articleExtensions[obj.ID]
	if ext == nil {
		return nil, nil
	}
	related := make([]*model.Article, len(ext.RelatedIDs))
	for i, rid := range ext.RelatedIDs {
		relatedExt := articleExtensions[rid]
		if relatedExt == nil {
			related[i] = &model.Article{ID: rid}
			continue
		}
		related[i] = toArticle(rid, relatedExt)
	}
	return related, nil
}

// Article returns generated.ArticleResolver implementation.
func (r *Resolver) Article() generated.ArticleResolver { return &articleResolver{r} }

type articleResolver struct{ *Resolver }
