name: Check Query Plan
on:
  workflow_call:
    inputs:
      router:
        type: string
      wgc:
        type: string
      token:
        type: string

jobs:
  check_query_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        name: Trigger Query Planner CI
        with:
          owner: wundergraph
          repo: cosmo-celestial
          ref: master
          github_token: ${{ inputs.token }}
          propagate_failure: true
          workflow_file_name: 'query-planner-tester.yaml'
          client_payload: >-
            {
              "router": "${{ inputs.router }}",
              "wgc": "${{ inputs.wgc }}",
              "token": "${{ inputs.token }}"
            }