name: WGC and Router CI
on:
  pull_request:
    paths:
      # This workflow should run every time router-ci and cli-ci runs
      - 'cli/**/*'
      - 'connect/**/*'
      - '.github/workflows/cli-ci.yaml'
      - 'composition-go/**/*'
      - 'demo/**/*'
      - 'router/**/*'
      - 'router-tests/**/*'
      - 'connect/**/*'
      - '.github/workflows/router-ci.yaml'
permissions:
  pull-requests: read
concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true
jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      router_changed: ${{ steps.filter.outputs.router }}
      cli_changed: ${{ steps.filter.outputs.cli }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Filter Changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            router:
              - 'demo/**/*'
              - 'router/**/*'
              - 'router-tests/**/*'
              - 'connect/**/*'
              - '.github/workflows/router-ci.yaml'
            cli:
              - 'cli/**/*'
              - 'connect/**/*'
              - '.github/workflows/cli-ci.yaml'
  call-router-ci:
    needs: filter-changes
    if: ${{ needs.filter-changes.outputs.router_changed == 'true' }}
    uses: ./.github/workflows/router-ci.yaml

  call-cli-ci:
    needs: filter-changes
    uses: ./.github/workflows/cli-ci.yaml
    if: ${{ needs.filter-changes.outputs.cli_changed == 'true' }}

  release-url:
    runs-on: ubuntu-latest
    if: ${{ needs.filter-changes.outputs.cli_changed != 'true' }}
    steps:
      - id: release-url
        run: |
          url=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/wundergraph/cosmo/releases --jq '.[] | select(.name | startswith("wgc@")) | .assets[] | select(.name | endswith("-bun-linux-x64.gz")) | .browser_download_url' | head -n 1`
          echo "wgc=$url" >> $GITHUB_OUTPUT
    outputs:
      wgc: ${{ steps.release-url.outputs.wgc }}
  check_query_plan:
    runs-on: ubuntu-latest
    needs: [ call-router-ci, call-cli-ci, release-url ]
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        name: Trigger Query Planner CI
        with:
          owner: wundergraph
          repo: cosmo-celestial
          ref: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          propagate_failure: true
          workflow_file_name: 'query-planner-tester.yaml'
          client_payload: >-
            {
              "router": "${{ needs.call-router-ci.outputs.router || 'ghcr.io/wundergraph/router:latest' }}",
              "wgc": "${{ needs.call-cli-ci.outputs.wgc || needs.release-url.outputs.wgc }}",
              "token": "${{ secrets.GITHUB_TOKEN }}"
            }