name: WGC and Router CI
on:
  pull_request:
    paths:
      # This workflow should run every time router-ci and cli-ci runs
      - 'cli/**/*'
      - 'connect/**/*'
      - '.github/workflows/cli-ci.yaml'
      - 'composition-go/**/*'
      - 'demo/**/*'
      - 'router/**/*'
      - 'router-tests/**/*'
      - 'connect/**/*'
      - '.github/workflows/router-ci.yaml'
permissions:
  pull-requests: read
concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true
jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.router }}
      frontend_changed: ${{ steps.filter.outputs.cli }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Filter Changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            router:
              - 'demo/**/*'
              - 'router/**/*'
              - 'router-tests/**/*'
              - 'connect/**/*'
              - '.github/workflows/router-ci.yaml'
            cli:
              - 'cli/**/*'
              - 'connect/**/*'
              - '.github/workflows/cli-ci.yaml'
  call-router-ci:
    needs: filter-changes
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/router-ci.yaml
        id: router-ci
        if: ${{ needs.filter-changes.outputs.router == 'true' }}
      - name: Set Router built image
        if: ${{ needs.filter-changes.outputs.router == 'true' }}
        run: echo "router=${{ steps.router-ci.outputs.router  }}" >> $GITHUB_OUTPUT
      - name: Set Router default image
        if: ${{ needs.filter-changes.outputs.router != 'true' }}
        run: echo "router=ghcr.io/wundergraph/router:latest" >> $GITHUB_OUTPUT
  call-cli-ci:
    needs: filter-changes
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/cli-ci.yaml
        id: cli-ci
        if: ${{ needs.filter-changes.outputs.cli == 'true' }}
      - name: Set Cli built artifact
        if: ${{ needs.filter-changes.outputs.router == 'true' }}
        run: echo "router=${{ steps.router-ci.outputs.router  }}" >> $GITHUB_OUTPUT
      - name: Set Router default image
        if: ${{ needs.filter-changes.outputs.router != 'true' }}
        run: echo "router=ghcr.io/wundergraph/router:latest" >> $GITHUB_OUTPUT
  check_query_plan:
    runs-on: ubuntu-latest
    needs: [ call-router-ci, call-cli-ci ]
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        name: Trigger Query Planner CI
        with:
          owner: wundergraph
          repo: cosmo-celestial
          ref: master
          github_token: ${{ inputs.token }}
          propagate_failure: true
          workflow_file_name: 'query-planner-tester.yaml'
          client_payload: >-
            {
              "router": "${{ needs.call-router-ci.outputs.router }}",
              "wgc": "${{ needs.call-cli-ci.outputs.cli }}",
              "token": "${{ secrets.GITHUB_TOKEN }}"
            }