name: Publish Helm Chart
run-name: Publish ${{ inputs.name }} Helm Chart
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-chart:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Helm version
        run: helm version

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Cosmo Chart
        working-directory: helm
        run: |
          make publish-cosmo-chart

      - name: Publish Router Chart
        working-directory: helm
        run: |
          make publish-router-chart
