name: Check PR Description
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate PR description
        uses: actions/github-script@v7
        with:
          script: |
            const prDescription = context.payload.pull_request.body || '';
            const minLength = 20; // Minimum required length for PR description
            
            // Extract content between "## Motivation and Context" and "## Checklist"
            const motivationRegex = /## Motivation and Context\s*([\s\S]*?)(?=## Checklist|$)/;
            const motivationMatch = prDescription.match(motivationRegex);
            const motivationContent = motivationMatch ? motivationMatch[1].trim() : '';
            
            if (!motivationContent || motivationContent.length < minLength) {
              core.setFailed(`The "Motivation and Context" section of your PR description is too short or missing. Please add a proper description of at least ${minLength} characters that explains the purpose of your changes. You can also use GitHub Copilot pull request summaries to help you write a good description.`);
              return;
            }
            
            // Check if description only contains comments
            const contentWithoutComments = motivationContent
              .replace(/<!--[\s\S]*?-->/g, '') // Remove HTML comments
              .trim();
              
            if (contentWithoutComments.length < minLength) {
              core.setFailed('The "Motivation and Context" section of your PR description contains mostly comments. Please add a proper description that explains the purpose of your changes.');
              return;
            }
            
            console.log('PR description "Motivation and Context" section is valid! ✅'); 