name: Release Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/release-preview.yaml'
      - '.github/workflows/release.yaml'
  push:
    tags-ignore:
      - '**'
    branches:
      - 'main'
    paths-ignore:
      - 'docs*/**'
      - '*.md'
      - '.github/CODEOWNERS'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

env:
  CI: true
  DO_NOT_TRACK: '1'

jobs:
  version:
    permissions:
      contents: read
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: Install
        run: pnpm install --frozen-lockfile --ignore-scripts --filter='wundergraph-cosmo'

      - name: Generate next release (dry-run)
        run: |
          git checkout -b release-preview
          pnpm run release-preview --yes --no-push --no-git-tag-version
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Show release preview
        run: |
          {
            echo '## Release preview'
            echo '```diff'
            git --no-pager diff -- './*/package.json' './*/CHANGELOG.md'
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
