name: Shared CI
on:
  pull_request:
    paths:
      - ".github/workflows/shared-ci.yaml"
      - "composition/**/*"
      - "connect/**/*"
      - "shared/**/*"

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate code
        run: pnpm buf generate --template buf.ts.gen.yaml

      - name: Check if git is not dirty after generating files
        run: git diff --no-ext-diff --exit-code

      - name: Build
        run: pnpm run --filter ./connect --filter ./shared --filter ./connect --filter ./composition build

      - name: Test
        run: pnpm run --filter ./shared test
